// oasisbet-react/src/component/AccountLogin.tsx
import React, { useState } from "react";
import './AccountLogin.css';
import { Card } from "react-bootstrap";

export default function AccountLanding(){
    
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = () => {
    console.log('Logging in... username: ', username, ' password: ', password);
    
  };

  return (
    <div className="container-fluid d-flex align-items-center justify-content-center">
      <Card className="card">
        <Card.Header className="card-header">
          <h2>Login</h2>
        </Card.Header>
        <Card.Body className="card-body d-flex flex-column align-items-center justify-content-center">
          <div className="form-group ">
            <label htmlFor="username">Username:</label>
            <input 
              type="text" 
              id="username" 
              value={username} 
              onChange={(e) => setUsername(e.target.value)} 
            />
          </div>
          <div className="form-group">
            <label htmlFor="password">Password:</label>
            <input 
              type="password" 
              id="password" 
              value={password} 
              onChange={(e) => setPassword(e.target.value)} 
            />
          </div>
          <br />
          <button className="login-btn" onClick={handleLogin}>Login</button>
          <hr/>
          <div className="form-group">
            <p>Don't have an account yet? <button className="signup-link">Sign Up Here</button></p>
          </div>
        </Card.Body>    
      </Card>
    </div>
  );
}

// oasisbet-frontend/src/app/account/account-login/account-login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/services/auth/auth.service';

@Component({
  selector: 'app-account-login',
  templateUrl: './account-login.component.html',
  styleUrls: ['./account-login.component.css']
})
export class AccountLoginComponent implements OnInit {

  username: string = "";
  password: string = "";
  errorMsg: string = "";
  responseMsg: string = "";

  constructor(private authService: AuthService) { }

  ngOnInit(): void {
  }

  handleJWTAuthLogin(){
    this.authService.jwtAuthenticate(this.username,this.password)
    .subscribe(
      data => {
        console.log(data);
        console.log("login successful");
      },
      error => {
        console.log("login fail");
        this.errorMsg = "Please enter a valid credential. Login failed.";
      }
    )
  }

  signUpUser(){
    console.log("signUpUser");
  }

}

<div class="container-fluid">
  <br>
  <div class="card col-md-6 offset-md-3">
    <div class="text-center">
      <h1 class="card-header">LOGIN</h1>
    </div>
    <div class="card-body">
      <div class="container-fluid">
        <div id="login-row" class="row justify-content-center align-items-center">
          <form id="login-column" class="col-md-6">
            <div *ngIf="responseMsg" class="alert alert-success">
              <b>Success: </b> {{responseMsg}}
            </div>
            <div class="alert alert-danger" *ngIf="errorMsg">{{errorMsg}}</div>
            <div id="login-box" class="col-md-12">
              <div id="login-form">
                <div class="form-group username-group">
                  <label for="username" class="username-label">Username:</label><br>
                  <input type="text" name="username" id="username" class="form-control" [(ngModel)]="username"
                    (ngModelChange)="username = $event.toUpperCase()">
                </div>
                <div class="form-group password-group">
                  <label for="password" class="username-label">Password:</label><br>
                  <input type="password" name="password" id="password" class="form-control" [(ngModel)]="password">
                </div>
                <div class="form-group btn-login-group">
                  <button id="authBtn" class="btn btn-success btn-login" (click)="handleJWTAuthLogin()">Login</button>
                </div>
                <hr>
                <div class="form-group others-group">
                  <p>Don't have an account yet? <a class="signup-link" (click)="signUpUser()">Sign Up Here</a></p>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- <div id="login">
  <h1 class="text-center text-white pt-5">Welcome to Trippify</h1>
  <div class="container">
    <div id="login-row" class="row justify-content-center align-items-center">

      <form id="login-column" class="col-md-6">
        <div *ngIf="responseMsg" class="alert alert-success">
          <b>Success: </b> {{responseMsg}}
        </div>
        <div class="alert alert-danger" *ngIf="errorMsg">{{errorMsg}}</div>
        <div id="login-box" class="col-md-12">
          <div id="login-form">

            <h2 class="text-center text-info">Login</h2>
            <div class="form-group">
              <label for="username" class="text-info">Username:</label><br>
              <input type="text" name="username" id="username" class="form-control" [(ngModel)]="username"
                (ngModelChange)="username = $event.toUpperCase()">
            </div>
            <div class="form-group">
              <label for="password" class="text-info">Password:</label><br>
              <input type="password" name="password" id="password" class="form-control" [(ngModel)]="password">
            </div>
            <div class="form-group username-group">
              <button id="authBtn" class="btn btn-success btn-login">Login</button>
            </div>
            <div class="form-group others-group">
              <p class="create-user-text" (click)="createUser()">Create New User</p>
            </div>
</div>
</div>
</form>
</div>
</div>
</div> -->
