// oasisbet-react/src/component/account/TrxHist.tsx
import React from "react";
import './TrxHist.css';
import { Card } from "react-bootstrap";
import SharedVarConstants from "../../constants/SharedVarConstants.js";
import SharedVarMethods from "../../constants/SharedVarMethods.js";

export default function TrxHist(){

    const trxHistList: any = [];

    return (
        <div className="container-fluid">
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Transaction History</h2>
                </Card.Header>
                <Card.Body className="card-body">
                <div>
                    <label className="trx-section-label-width">Month To Date</label>
                    <br />
                    <label className="trx-section-label-width">Bet Placed:</label>
                    <span className="col-sm-3 trx-section-selection-width">$5568.10</span>
                    <br />
                    <label className="trx-section-label-width">Payout:</label>
                    <span className="col-sm-3 trx-section-selection-width">$6421.42</span>
                    <hr />
                    <div className="row">
                        <div className="col-md-3 offset-md-1">
                        <label className="trx-section-label-width">View</label>
                        <div className="dropdown-section">
                            <select id="trxViewDropdown" className="trx-dropdown">
                                <option value="funds">Funds In/Out</option>
                                <option value="sportsbet">All Sports Bet</option>
                                <option value="deposit">Deposits</option>
                                <option value="withdrawal">Withdrawals</option>
                            </select>
                        </div>
                        </div>
                        <div className="col-md-3 offset-md-1">
                        <label className="trx-section-label-width">Time Period</label>
                        <div className="dropdown-section">
                            <select id="trxTimePrdDropdown" className="trx-dropdown">
                                <option value="today">Today</option>
                                <option value="last7day">Last 7 Days</option>
                                <option value="last1mth">Last Month</option>
                                <option value="last3mth">Last 3 Months</option>
                                <option value="last6mth">Last 6 Months</option>
                            </select>
                        </div>
                        </div>
                    </div>
                    <br />
                    <table className="table" style={{ tableLayout: 'fixed', width: '100%' }}>
                        <thead className="table-header-trx">
                        <tr>
                            <th style={{ textAlign: 'center', width: '25%' }}>Date & Time</th>
                            <th style={{ textAlign: 'center', width: '45%' }}>Description</th>
                            <th style={{ textAlign: 'center', width: '20%' }}>Amount</th>
                            <th style={{ textAlign: 'center', width: '10%' }}></th>
                        </tr>
                        </thead>
                        <tbody>
                        {trxHistList.map((trx, index) => (
                            <React.Fragment key={index}>
                            <tr>
                                <td style={{ textAlign: 'center', width: '25%' }}>
                                    {new Date(trx.dateTime).toLocaleString()}
                                </td>
                                <td style={{ textAlign: 'center', width: '45%' }}>
                                    {trx.desc}
                                </td>
                                <td style={{ textAlign: 'center', width: '20%' }}>
                                    {trx.type === 'W' || trx.type === 'S' ? `-$${trx.amount.toFixed(2)}` : `+$${trx.amount.toFixed(2)}`}
                                </td>
                                    <td style={{ textAlign: 'center', width: '10%' }}>
                                </td>
                            </tr>
                            {trx.showDetails && trx.trxBetDetails && (
                                <tr>
                                <td colSpan={4}>
                                    <table className="table" style={{ tableLayout: 'fixed', width: '100%' }}>
                                    <thead className="table-header-details">
                                        <tr>
                                        <th style={{ textAlign: 'center', width: '20%' }}>Start Time</th>
                                        <th style={{ textAlign: 'center', width: '15%' }}>Competition</th>
                                        <th style={{ textAlign: 'center', width: '25%' }}>Bet Details</th>
                                        <th style={{ textAlign: 'center', width: '10%' }}>Bet Type</th>
                                        <th style={{ textAlign: 'center', width: '10%' }}>Status</th>
                                        <th style={{ textAlign: 'center', width: '20%' }}>Bet Receipt</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                        <td style={{ textAlign: 'center', width: '20%' }}>{new Date(trx.trxBetDetails.startTime).toLocaleString()}</td>
                                        <td style={{ textAlign: 'center', width: '15%' }}>{trx.trxBetDetails.compType}</td>
                                        <td style={{ textAlign: 'center', width: '25%' }}>{trx.trxBetDetails.betDetails}</td>
                                        <td style={{ textAlign: 'center', width: '10%' }}>{SharedVarMethods.mapBetTypeCd(trx.trxBetDetails.betType)}</td>
                                        <td style={{ textAlign: 'center', width: '10%' }}>{trx.trxBetDetails.status ? SharedVarConstants.SETTLED : SharedVarConstants.NOT_SETTLED}</td>
                                        <td style={{ textAlign: 'center', width: '20%' }}>{trx.trxBetDetails.trxId}</td>
                                        </tr>
                                    </tbody>
                                    </table>
                                </td>
                                </tr>
                            )}
                            </React.Fragment>
                        ))}
                        {(!trxHistList || trxHistList.length === 0) && (
                            <tr>
                            <td className="text-center" colSpan={6}>
                                No Transaction(s) Found.
                            </td>
                            </tr>
                        )}
                        </tbody>
                    </table>
                    </div>
                </Card.Body> 
            </Card>
        </div>
    );
}

// oasisbet-frontend/src/app/account/trx-hist/trx-hist.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-trx-hist',
  templateUrl: './trx-hist.component.html',
  styleUrls: ['./trx-hist.component.css']
})
export class TrxHistComponent implements OnInit {

  placeholderView = "Please select a view";
  items: string[] = ["test1", "test2"];
  
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card " >
    <div class="text-left">
        <h1 class="card-header">Transaction History</h1>
    </div>
    <div class="card-body">
        <div class="alert alert-danger col-md-10 offset-md-1" *ngIf="errorMsg"> <b>Fail: </b> {{errorMsg}}</div>
        <label class="control-label trx-section-label-width">Month To Date</label>
        <br>
        <label class="control-label trx-section-label-width">Bet Placed:</label>
        <span class="col-sm-3 trx-section-selection-width">${{mtdBetAmount}}</span>
        <br>
        <label class="control-label trx-section-label-width">Payout:</label>
        <span class="col-sm-3 trx-section-selection-width">$0</span>
        <hr>
        <div class="row">
            <div class="col-md-3 offset-md-1">
                <label class="control-label trx-section-label-width">View</label>
                <div class="dropdown-section">
                    <select [(ngModel)]="selectedTrxType" (ngModelChange)="ngOnInit()" id="trxViewDropdown"
                      class="form-control trx-dropdown">
                        <option value="funds">Funds In/Out</option>
                        <option value="sportsbet">All Sports Bet</option>
                        <option value="deposit">Deposits</option>
                        <option value="withdrawal">Withdrawals</option>
                    </select>
                    <span class="dropdown-icon"><i class="fas fa-angle-down"></i></span>
                </div>
            </div>
            <div class="col-md-3 offset-md-1">
                <label class="control-label trx-section-label-width">Time Period</label>
                <div class="dropdown-section">
                    <select [(ngModel)]="selectedPeriod" (ngModelChange)="ngOnInit()" id="trxTimePrdDropdown"
                      class="form-control trx-dropdown">
                        <option value="today">Today</option>
                        <option value="last7day">Last 7 Days</option>
                        <option value="last1mth">Last Month</option>
                        <option value="last3mth">Last 3 Months</option>
                        <option value="last6mth">Last 6 Months</option>
                    </select>
                    <span class="dropdown-icon"><i class="fas fa-angle-down"></i></span>
                </div>
            </div>
        </div>
        <br>
        <table class="table" style="table-layout: fixed; width: 100%;">
            <thead class= "table-header">
                <tr>
                  <th style="text-align:center; width: 25%;">Date & Time</th>
                  <th style="text-align:center; width: 45%;">Description</th>
                  <th style="text-align:center; width: 20%;">Amount</th>
                  <th style="text-align:center; width: 10%;"></th>
                </tr>
            </thead>
            <tbody>
              <ng-container *ngFor="let trx of trxHistList">
                <tr>
                  <td style="text-align:center; width: 25%;">{{trx.dateTime | date:'medium'}}</td>
                  <td style="text-align:center; width: 45%;">{{trx.desc}}</td>
                  <td style="text-align:center; width: 20%;">{{trx.type == 'W' || trx.type == 'S' ? '-$' + (trx.amount | number : '1.2-2') : '+$' + (trx.amount | number : '1.2-2') }}</td>
                  <td style="text-align:center; width: 10%;">
                    <i class="fas" *ngIf="trx.type == 'S' || trx.type == 'C'" [ngClass]="{'fa-angle-right': !trx.showDetails, 'fa-angle-down': trx.showDetails}"  
                    (click)="toggleShowDetails(trx)" ></i>
                  </td>
                </tr>
                <tr *ngIf="trx.showDetails && trx.trxBetDetails">
                  <td colspan="4">
                    <table class="table" style="table-layout: fixed; width: 100%;">
                      <thead class="table-header">
                        <tr>
                          <th style="text-align:center; width: 20%;">Start Time</th>
                          <th style="text-align:center; width: 15%;">Competition</th>
                          <th style="text-align:center; width: 25%;">Bet Details</th>
                          <th style="text-align:center; width: 10%;">Bet Type</th>
                          <th style="text-align:center; width: 10%;">Status</th>
                          <th style="text-align:center; width: 20%;">Bet Receipt</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td style="text-align:center; width: 20%;">{{trx.trxBetDetails.startTime | date:'medium'}}</td>
                          <td style="text-align:center; width: 15%;">{{trx.trxBetDetails.compType}}</td>
                          <td style="text-align:center; width: 25%;">{{trx.trxBetDetails.betDetails}}</td>
                          <td style="text-align:center; width: 10%;">{{sharedVar.mapBetTypeCd(trx.trxBetDetails.betType)}}</td>
                          <td style="text-align:center; width: 10%;">{{trx.trxBetDetails.status ? sharedVar.SETTLED : sharedVar.NOT_SETTLED}}</td>
                          <td style="text-align:center; width: 20%;">{{trx.trxBetDetails.trxId}}</td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </ng-container>
              
              <tr *ngIf='!trxHistList || trxHistList.length == 0'>
                <td class='text-center' colspan=12>
                  No Transaction(s) Found.
                </td>
              </tr>
            </tbody>
        </table>
    </div>
</div>
