// oasisbet-react/src/component/account/Withdrawals.tsx
import React from "react";
import './Withdrawals.css';
import { Card } from "react-bootstrap";

export default function Withdrawals(){

    return (
        <div className="container-fluid">
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Withdrawals</h2>
                </Card.Header>
                <Card.Body className="card-body">
                <label className="control-label col-xs-6 col-sm-3 col-md-3 withdraw-section-label-width">Balance:</label>
                    <span className="col-xs-6 col-sm-3 col-md-2 withdraw-section-selection-width">$100.00</span>
                    <br />
                    <br />
                    <span className="control-label check-trx-hist-note">
                        Note: Check <a href="#trxHist" onClick={() => {/* navToTrxHistMenu() */}}>transaction history</a> for more details.
                    </span>
                    <hr />
                    <form>
                        <div className="form-group row">
                        <label id="WITHDRAWAL_LABEL_1" htmlFor="withdrawal_0_Label" className="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">
                            <span id="WITHDRAWAL">Withdraw from OasisBet Account:</span>
                        </label>
                        <div className="col-sm-4">
                            <div className="input-group">
                            <div className="input-group-prepend">
                                <span className="input-group-text">$</span>
                            </div>
                            <input id="withdrawalAmt_0" type="text" className="form-control allCaps" name="withdrawalAmt" />
                            </div>
                        </div>
                        </div>
                        <br />
                        <div className="form-group row">
                        <label id="PASSWORD_LABEL_1" htmlFor="password_0_Label" className="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">
                            <span id="PASSWORD">Enter OasisBet Account password:</span>
                        </label>
                        <div className="col-sm-4">
                            <div className="input-group">
                            <div className="input-group-prepend"></div>
                            <input type="password" className="form-control withdraw-section-selection-width no-spinner" id="password_0" name="password" required />
                            </div>
                        </div>
                        </div>
                    </form>
                    <hr />
                    <div className="dialog-actions">
                        <button className="btn btn-danger btn-cancel" type="button" onClick={() => {/* onCancelWithdrawal() */}}>
                        Cancel
                        </button>
                        <button className="btn btn-success btn-confirm" type="button" onClick={() => {/* confirmClicked() */}}>
                        Confirm
                        </button>
                    </div>
                    <br />
                </Card.Body> 
            </Card>
        </div>
    );
}

// oasisbet-frontend/src/app/account/withdrawals/withdrawals.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { AccountModel } from 'src/app/model/account.model';
import { AuthService } from 'src/app/services/auth/auth.service';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-withdrawals',
  templateUrl: './withdrawals.component.html',
  styleUrls: ['./withdrawals.component.css']
})
export class WithdrawalsComponent implements OnInit {

  accountModelInput: AccountModel;
  @Output() onSelectTrxMenu: EventEmitter<string>;

  constructor(public sharedVar: SharedVarService, private authService: AuthService) {
    this.onSelectTrxMenu = new EventEmitter<string>();
  }

  ngOnInit(): void {
    this.accountModelInput = this.authService.getRetrievedAccDetails();
  }

  navToTrxHistMenu(){
    this.onSelectTrxMenu.emit(this.sharedVar.NAV_MENU_SELECT_TRX_HIST);
  }

  onCancelWithdrawal(){

  }

  onConfirmWithdrawal(){
    
  }
}

<div class="card" >
    <div class="text-left">
        <h1 class="card-header">Withdrawals</h1>
    </div>
    <div class="card-body">
        <label class="control-label col-xs-6 col-sm-3 col-md-3 withdraw-section-label-width">Balance:</label>
        <span class="col-xs-6 col-sm-3 col-md-2 withdraw-section-selection-width">${{accountModelInput?.balance}}</span>
        <br>
        <br>
        <span class="control-label check-trx-hist-note">Note: Check <a (click)="navToTrxHistMenu()">transaction history</a> for more details.</span>
        <hr>
        <form [formGroup]="withdrawalForm">
          <div class="form-group row">
            <label id="WITHDRAWAL_LABEL_1" for="withdrawal_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(withdrawalAmt)}" class="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">
              <span id="WITHDRAWAL">Withdraw from OasisBet Account:</span>
            </label>
            <div class="col-sm-4">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">$</span>
                </div>
                <input id="withdrawalAmt_0" type="text" maxlength="9" class="form-control allCaps" formControlName="withdrawalAmt" name="withdrawalAmt">
              </div>
              <label id="withdrawalAmt_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(withdrawalAmt)}" class="error-text"
                for="withdrawalAmt_0">
                <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(withdrawalAmt)) == 'pattern'">Please enter only 1 or 2 decimal places</span>
                <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(withdrawalAmt)) == 'maxAmount'">Maximum amount to withdraw is $199999.99</span>
                <span *ngIf="withdrawalAmt.hasError('notZero')">Withdrawal amount cannot be 0</span>
                <span *ngIf="withdrawalAmt.hasError('required') && !withdrawalAmt.value && !withdrawalAmt.pristine">This field is required</span>
              </label>
            </div>
          </div>
          <br>
          <br>
          <div class="form-group row">
            <label id="PASSWORD_LABEL_1" for="password_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">
              <span id="PASSWORD">Enter OasisBet Account password:</span>
            </label>
            <div class="col-sm-4">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">$</span>
                </div>
                <input type="password" class="form-control withdraw-section-selection-width no-spinner" formControlName="password" id="password_0" name="password" required>
              </div>
              <label id="password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="error-text"
                for="password_0">
                <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'maxlength'">Maximum length is 20
                  characters</span>
                <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'minlength'">Minimum length is 5
                  characters</span>
                <span *ngIf="password.hasError('required') && !password.value && !password.pristine">This field is
                  required</span>
              </label>
            </div>
          </div>
        </form>
        <!-- <div class="form-group row">
            <label class="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">Withdraw from OasisBet Account:</label>
            <div class="col-sm-4">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">$</span>
                </div>
                <input type="number" class="form-control withdraw-section-selection-width no-spinner" id="withdrawAmount" name="withdrawAmount" required>
              </div>
            </div>
        </div>
        <br>
        <br>
        <div class="form-group row">
            <label class="control-label col-sm-4 withdraw-section-label-width withdraw-acc-label-text">Enter OasisBet Account password:</label>
            <div class="col-sm-4">
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">$</span>
                </div>
                <input type="password" class="form-control withdraw-section-selection-width no-spinner" id="password" name="password" required>
              </div>
            </div>
        </div> -->
        <hr>
        <div mat-dialog-actions align="end">
            <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelWithdrawal()">
                Cancel
            </button>
            <button class="btn btn-success btn-confirm" type="button" (click)="onConfirmWithdrawal()">
                Confirm
            </button>
          </div>
    </div>
</div>
