// oasisbet-react/src/component/odds/OddsBetSlip.tsx
import React, { useEffect, useState } from "react";
import './OddsBetSlip.css';
import { faAngleDown } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useDispatch, useSelector } from "react-redux";
import { submitBets } from "../../services/api/ApiService.ts";
import { SubmitBetsModel } from "../../model/SubmitBetsModel";
import { useNavigate } from "react-router-dom";
import SharedVarConstants from "../../constants/SharedVarConstants.ts";
import { AccountModel } from "../../constants/Modal.ts";
import SharedVarMethods from "../../constants/SharedVarMethods.ts";
import { updateLoginDetails } from "../actions/ReducerAction.ts";
import { openAlert } from "../actions/ReducerAction.ts";

export default function OddsBetSlip({onBetSlipUpdate, onPlaceBetStatusUpdate, placeBetStatus}){
    const dispatch = useDispatch();
    const navigate = useNavigate();

    const betEvents = useSelector((state: any) => state.betSlip.betSlip);
    const reducerAction = useSelector((state: any) => state.betSlip.action);
    const [responseMsg, setResponseMsg] = useState('');
    const [errorMsg, setErrorMsg] = useState('');
    const [betSlipSelections, setBetSlipSelections] = useState([]) as any;
    const [showSingles, setShowSingles] = useState(true);
    const [totalStake, setTotalStake] = useState(0);

    useEffect(() => {
        let updatedTotalStake = 0;
        betEvents.forEach(event => updatedTotalStake += event.betAmount);
        setTotalStake(updatedTotalStake);

        setBetSlipSelections(() => {
            if (reducerAction === 'ADD') {
                setResponseMsg('');
                setErrorMsg('');
            }
            return betEvents;
        });
    }, [betEvents, reducerAction]);

    function handleClickSingles(): void {
        setShowSingles(prevState => !prevState);
    }

    function handleOnDelete(betEvent): void {
        let updateBetEvents = [...betSlipSelections];
        updateBetEvents = updateBetEvents.filter(e => !(e.eventId === betEvent.eventId && e.betSelection === betEvent.betSelection));
        onBetSlipUpdate(betEvent);
        let updatedTotalStake = 0;
        updateBetEvents.forEach(event => updatedTotalStake += event.betAmount);
        setTotalStake(updatedTotalStake);
        dispatch({type: 'REMOVE_BET_SELECTION', payload: updateBetEvents});
    }

    function handleChangeBetAmount(betEvent, event){
        const regex = /^(?!0\d*$)\d{1,4}(?:\.\d{0,2})?$/;
        let amount = event.target.value;
        if(!regex.test(amount)){
            betEvent.betAmount = null;
            betEvent.potentialPayout = 0;
        } else {
            amount = +amount;
            betEvent.betAmount = amount;
            const odds = +betEvent.odds;
            betEvent.potentialPayout = +(odds * amount).toFixed(2);
        }
        
        let updatedTotalStake = 0;
        const updatedBetSlip = betSlipSelections.map(betSelection => {
            updatedTotalStake += betSelection.betAmount;
            if(betSelection.eventId === betEvent.eventId && betSelection.betSelection === betEvent.betSelection){
                return betEvent;
            }
            return betSelection;
        });
        setBetSlipSelections(updatedBetSlip);
        setTotalStake(updatedTotalStake);
    }

    function handleClickPlaceBet(): void {
        const betSelectionsWithNoAmt = betSlipSelections.filter(e => e.betAmount === 0 || e.potentialPayout === 0);
        let updateBetEvents = [...betSlipSelections];
        console.log("vincent betSelectionsWithNoAmt: ", betSelectionsWithNoAmt)
        betSelectionsWithNoAmt.forEach(removeSelection => {
            updateBetEvents = updateBetEvents.filter(e => !(e.eventId === removeSelection.eventId && e.betSelection === removeSelection.betSelection));
            onBetSlipUpdate(removeSelection);
            dispatch({type: 'REMOVE_BET_SELECTION', payload: updateBetEvents});
        });
        console.log("vincent after: ")
        onPlaceBetStatusUpdate("C");
    }

    function handleClickDecline(): void {
        onPlaceBetStatusUpdate("I");
    }

    const handleClickConfirmBet = async (dispatch, betEvents, onPlaceBetStatusUpdate) => {
        dispatch({ type: 'CLEAR_BET_SELECTION' });
        onPlaceBetStatusUpdate("D");
        console.log("confirm place bet! betPLaced: ", betEvents);

        const accountDetailsString = sessionStorage.getItem(SharedVarConstants.ACCOUNT_DETAILS);
        const accountDetails: AccountModel = accountDetailsString ? JSON.parse(accountDetailsString) : {};
        const { accId } = accountDetails;
        
        const submitBetsModel: SubmitBetsModel = {
            userId: accId,
            betSlip: betEvents
        };

        try {
            const response = await submitBets(submitBetsModel);
            console.log("Bet submission response:", response);
            if(response.statusCode === 0){
                setResponseMsg(response.resultMessage);
                sessionStorage.setItem(SharedVarConstants.ACCOUNT_DETAILS, JSON.stringify(response.account));
                dispatch(updateLoginDetails('balance', response.account?.balance));
            } else if (response.statusCode === 4) {
                SharedVarMethods.clearSessionStorage();
                dispatch(updateLoginDetails('isUserLoggedIn', false));
                navigate('/account', { state: { code: 1, message: response.resultMessage } });
                return;
            } else {
                setErrorMsg(response.resultMessage);
            }
        } catch (error) {
            dispatch(openAlert(error.message));
            setErrorMsg("There is an error with the process");
        }
    };

    return (
        betSlipSelections.length > 0 && 
        <div className="bet-slip">
            <h2 className="bet-slip-header">Bet Slip</h2>
            {responseMsg && <div className="alert alert-success"><b>Success: </b>{responseMsg}</div>}
            {errorMsg && <div className="alert alert-danger"><b>Fail: </b>{errorMsg}</div>}
            <div className="header-panel">
                <h3 className="panel-header" onClick={handleClickSingles}>Singles
                    <span className="dropdown-icon">
                        <FontAwesomeIcon icon={faAngleDown} />
                    </span>
                </h3>
                <br />
                {showSingles && 
                    <div className="selections">
                        <div className="bet-slip-container">
                            <div className="container">
                                {betSlipSelections.map(betEvent => {
                                    return (
                                        <div key={betEvent.eventId + '_' + betEvent.betSelection}>
                                            <div className="row">
                                                <div className="col-md-10">
                                                    <p className="event-description">{betEvent.eventDesc}</p>
                                                </div>
                                                {placeBetStatus !== 'D' &&  
                                                    <div className="col-md-2" onClick={() => handleOnDelete(betEvent)}>
                                                        <p className="delete-icon" aria-label='Delete Icon'>&#10005;</p>
                                                    </div>
                                                }
                                            </div>
                                            <div className="row">
                                                <p className="bet-type">1X2</p>
                                            </div>
                                            <div className="row">
                                                <div className="col-md-8">
                                                    <p className="bet-selection">{betEvent.betSelectionName} @ {betEvent.odds}</p>
                                                </div>    
                                                <div className="col-md-4">
                                                    {placeBetStatus === 'I' && 
                                                        <span className="bet-amount-input">
                                                            $<input type="text" maxLength={7} inputMode="numeric" aria-label="Bet Amount"
                                                                value={betEvent.betAmount !== null ? betEvent.betAmount : ''}
                                                                onChange={(event) => handleChangeBetAmount(betEvent, event)}/>
                                                        </span>
                                                    }
                                                    {placeBetStatus !== 'I' && betEvent.potentialPayout !== 0 &&
                                                        <span className="pull-right" style={{float: 'right'}}>
                                                            $  {betEvent.betAmount}
                                                        </span>
                                                    }
                                                </div>    
                                            </div>
                                            <hr />
                                            <div className="row">
                                                <p className="potential-payout-text">Potential Payout: ${betEvent.potentialPayout.toFixed(2)}</p>
                                            </div>
                                        </div>
                                    )
                                })}
                                
                            </div>
                            <br/>
                        </div>
                    </div>
                }

                <div className="total-stake-panel">
                    <span className="total-stake-section">Total Stake: ${totalStake}</span>
                </div>
                {placeBetStatus === 'I' && 
                    <button className="btn btn-success btn-place-bet" type="button" onClick={handleClickPlaceBet} disabled={totalStake === 0}>
                        Place Bet
                    </button>
                }
                {placeBetStatus === 'C' && 
                    <div className="row">
                        <div className="col-md-6 d-flex justify-content-center">
                            <button className="btn btn-success btn-decline" type="button" onClick={handleClickDecline}>
                                Decline
                            </button>
                        </div>
                        <div className="col-md-6 d-flex justify-content-center">
                            <button className="btn btn-success btn-confirm" type="button" onClick={() => handleClickConfirmBet(dispatch, betEvents, onPlaceBetStatusUpdate)}>
                                Confirm
                            </button>
                        </div>
                    </div>
                }
                
            </div>
        </div>
    );
}

// oasisbet-frontend/src/app/odds/odds-bet-slip/odds-bet-slip.component.ts
import { Component, EventEmitter, Input, OnInit, Output, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { Observable, Subscription } from 'rxjs';
import { AccountModel } from 'src/app/model/account.model';
import { BetSlip } from 'src/app/model/bet-slip.model';
import { BetsModel } from 'src/app/model/bets.model';
import { ResponseModel } from 'src/app/model/response.model';
import { ApiService } from 'src/app/services/api/api.service';
import { ACC_DETAILS, AuthService } from 'src/app/services/auth/auth.service';
import { SharedMethodsService } from 'src/app/services/shared-methods.service';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-odds-bet-slip',
  templateUrl: './odds-bet-slip.component.html',
  styleUrls: ['./odds-bet-slip.component.css']
})
export class OddsBetSlipComponent implements OnInit {

  public responseMsg: string = '';
  @Input() public errorMsg: string = '';

  public showSinglesSelection: boolean = true;
  public showMultiplesSelection: boolean = true;
  public totalStake: number = 0;

  public placedBetStatus: number = 1; //before place bet = 1
                                      //after place bet, before confirm = 2
                                      //after confirm, bet successful = 3

  @Input() betSelections: BetSlip[];
  @Output() enableBets: EventEmitter<void> = new EventEmitter<void>();
  @Output() betSelectionsChange: EventEmitter<BetSlip[]> = new EventEmitter<BetSlip[]>();
  @Output() removedBetSelection: EventEmitter<BetSlip> = new EventEmitter<BetSlip>();
  @Output() removeAllBetSelections: EventEmitter<void> = new EventEmitter<void>();

  public betSlipSubscription: Subscription;
  public subscriptions: Subscription = new Subscription();

  @Input() initBetSlip: Observable<void>;

  constructor(
    public sharedVar: SharedVarService,
    public apiService: ApiService,
    public router: Router,
    public authService: AuthService) { }

  ngOnInit(): void {
    this.betSlipSubscription = this.initBetSlip.subscribe(() => {
      this.placedBetStatus = 1;
      this.responseMsg = "";
      this.errorMsg = "";
      this.totalStake = 0;
    });
  }

  toggleSelection(selectionType: string): void {
    if (selectionType === 'singles') {
      this.showSinglesSelection = !this.showSinglesSelection;
    } else if (selectionType === 'multiples') {
      this.showMultiplesSelection = !this.showMultiplesSelection;
    }
  }

  onDeleteBetSelection(betSelection: BetSlip){
    this.betSelections = this.betSelections.filter(e => !(e.eventId === betSelection.eventId && e.betSelection === betSelection.betSelection));
    this.totalStake = 0;
    this.betSelections.forEach(selection => this.totalStake =  this.totalStake + selection.betAmount);
    this.removedBetSelection.emit(betSelection);
    if(this.betSelections.length === 0){
      this.placedBetStatus = 1;
      this.enableBets.emit();
    }
  }

  onBetAmountChange(betSlipItem: BetSlip, betAmount: string) {
    const regex = /^(?!0\d*$)\d{1,4}(?:\.\d{0,2})?$/;
    if(!regex.test(betAmount)){
      betSlipItem.betAmount = null;
      betSlipItem.potentialPayout = 0;
    } else {
      betSlipItem.betAmount = parseFloat(Number(betAmount).toFixed(2));
      betSlipItem.potentialPayout = parseFloat((betSlipItem.betAmount * betSlipItem.odds).toFixed(2));
    }
    this.totalStake = 0;
    this.betSelections.forEach(selection => this.totalStake =  this.totalStake + selection.betAmount);
  }

  onPlaceBets(){
    this.errorMsg = "";

    //remove bet selections that does not have bet amount
    const removedBetSelections = this.betSelections.filter(e => e.betAmount === 0 || e.potentialPayout === 0);
    this.betSelections = this.betSelections.filter(e => e.betAmount !== 0 && e.potentialPayout !== 0);
    this.placedBetStatus = 2;
    this.betSelectionsChange.emit(removedBetSelections);
  }

  onCancelPlaceBets(){
    this.betSelections.forEach(selection => {
      selection.betAmount = null;
      selection.potentialPayout = 0;
    });
    this.totalStake = 0;
    this.placedBetStatus = 1;
    this.enableBets.emit();
  }

  onFinalConfirmPlaceBets(){
    // call backend api here to place bet
    this.sharedVar.submitBetsModel.betSlip = this.betSelections;
    const account: AccountModel = this.authService.getRetrievedAccDetails();
    if(!account || !account.accId){
      this.sharedVar.changeShowUserNotLoginMsg(this.sharedVar.USER_NOT_LOGGED_IN);
      this.router.navigate(['account']);
      return;
    }
    this.sharedVar.submitBetsModel.userId = account.accId;
    this.subscriptions.add(
      this.apiService.postSubmitBets().subscribe( (resp: any) => {
        if (resp.statusCode != 0) {
          this.errorMsg = resp.resultMessage;
          resp.resultMessage = "";
        } else {
          //if success, clear the current bet selections
          this.removeAllBetSelections.emit();

          this.responseMsg = resp.resultMessage;
          this.placedBetStatus = 3;

          let accountModel: AccountModel = new AccountModel();
          accountModel = this.authService.getRetrievedAccDetails();
          if (resp && resp.account && accountModel) {
            accountModel.balance = resp.account.balance;
            sessionStorage.setItem(ACC_DETAILS, JSON.stringify(accountModel));
          }
        }
      } ,
        error => {
        this.sharedVar.changeException(error);
      })
    );
  }

  ngOnDestroy() {
    this.betSlipSubscription.unsubscribe();
    this.subscriptions.unsubscribe();
  }

}

<div class="bet-slip">
    <h2 class="bet-slip-header">Bet Slip</h2>
    
    <div class="alert alert-success" *ngIf="responseMsg" ><b>Success: </b> {{responseMsg}}</div>
    <div class="alert alert-danger" *ngIf="errorMsg"><b>Fail: </b>{{errorMsg}}</div>
    <div *ngIf="betSelections && betSelections.length > 0">
      <div class="header-panel">
        <h3 class="panel-header" (click)="toggleSelection('singles')">Singles<span class="dropdown-icon" ><i class="fas fa-angle-down"></i></span></h3>
        <div class="selections" *ngIf="showSinglesSelection">
          <div class="bet-slip-container" *ngFor="let betSelection of betSelections">
            <div class="container" *ngIf="!placedBetConfirmFlag || (betSelection.potentialPayout != 0 && placedBetConfirmFlag)">
              <div class="row">
                <div class="col-md-9">
                  <p class="event-description">{{ betSelection.eventDesc }}</p>
                  <p class="bet-type">{{ sharedVar.mapBetTypeCd(betSelection.betTypeCd) }}</p>
                  <p class="bet-selection">{{ betSelection.betSelectionName }} @ {{ betSelection.odds }}</p>
                </div>
                <div class="col-md-3">
                  <p class="delete-icon" (click)="onDeleteBetSelection(betSelection)">&#10005;</p>
                  <span class="bet-amount-input">
                    $<input #betAmountInput type="text" class="form-control" autocomplete="off" maxlength="7" inputmode="numeric" 
                    [value]="betSelection.betAmount"
                    *ngIf = "!placedBetConfirmFlag"
                    (input)="onBetAmountChange(betSelection, betAmountInput.value)">
                    <span *ngIf = "(betSelection.potentialPayout != 0 && placedBetConfirmFlag)">{{betSelection.betAmount | number : '1.2-2'}}</span>
                  </span>
                </div>
                <hr>
              </div>
              <div class="row">
                <p class="potential-payout-text">Potential Payout: ${{ betSelection.potentialPayout | number : '1.2-2' }}</p>
              </div>
            </div>
            <br>
          </div>

        </div>
      </div>
      <div class="total-stake-panel">
        <span class="total-stake-section">Total Stake: ${{totalStake}}</span>
      </div>
      <button class="btn btn-success btn-place-bet" *ngIf="!placedBetConfirmFlag" type="button" (click)="onPlaceBets()" [disabled]="!totalStake || totalStake === 0">
        Place Bet
      </button>
      <div class="row" *ngIf="placedBetConfirmFlag">
        <div class="col-md-6 d-flex justify-content-center">
          <button class="btn btn-success btn-decline" *ngIf="placedBetConfirmFlag" type="button" (click)="onCancelPlaceBets()">
            Decline
          </button>
        </div>
        <div class="col-md-6 d-flex justify-content-center">
          <button class="btn btn-success btn-confirm" *ngIf="placedBetConfirmFlag" type="button" (click)="onFinalConfirmPlaceBets()">
            Confirm
          </button>
        </div>
      </div>
    </div>

    <div class="empty-bet-slip" *ngIf="!betSelections || betSelections.length == 0">
        <p>Your bet slip is empty.</p>
    </div>
    
    
    <!-- <div class="header-panel" (click)="toggleSelection('multiples')">
      <h3 class="panel-header">Multiples<span class="dropdown-icon"><i class="fas fa-angle-down"></i></span></h3>
      <div class="selections" *ngIf="showMultiplesSelection">
        <p>Multiple Bet Selection</p>
      </div>
    </div>  -->
</div>
