// oasisbet-react/src/component/common/CompSideNav.tsx
import React from 'react';
import './CompSideNav.css';
import SharedVarConstants from '../../constants/SharedVarConstants.ts';

function CompSideNav({ compType, selectCompType }) {
    return (
        <div className="sidebar">
            <ul>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_EPL ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_EPL)}>{SharedVarConstants.COMP_HEADER_EPL}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_LALIGA ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_LALIGA)}>{SharedVarConstants.COMP_HEADER_LALIGA}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_BUNDESLIGA ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_BUNDESLIGA)}>{SharedVarConstants.COMP_HEADER_BUNDESLIGA}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_SERIE_A ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_SERIE_A)}>{SharedVarConstants.COMP_HEADER_SERIE_A}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_LIGUE_ONE ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_LIGUE_ONE)}>{SharedVarConstants.COMP_HEADER_LIGUE_ONE}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_FA_CUP ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_FA_CUP)}>{SharedVarConstants.COMP_HEADER_FA_CUP}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_EFL_CUP ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_EFL_CUP)}>{SharedVarConstants.COMP_HEADER_EFL_CUP}</li>
                <li className={`sidebar-item ${compType === SharedVarConstants.API_SOURCE_COMP_TYPE_UCL ? 'highlightSideNav' : ''}`} onClick={() => selectCompType(SharedVarConstants.API_SOURCE_COMP_TYPE_UCL)}>{SharedVarConstants.COMP_HEADER_UCL}</li>
            </ul>
        </div>
    );
}
  
export default CompSideNav;

// oasisbet-frontend/src/app/views/d-comp-side-nav/comp-side-nav/comp-side-nav.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-comp-side-nav',
  templateUrl: './comp-side-nav.component.html',
  styleUrls: ['./comp-side-nav.component.css']
})
export class CompSideNavComponent implements OnInit {

  @Output() onSelectCompType : EventEmitter<string>;
  compType: string = this.sharedVar.API_SOURCE_COMP_TYPE_EPL;

  constructor(public sharedVar: SharedVarService) { 
    this.onSelectCompType = new EventEmitter<string>();
  }

  ngOnInit(): void {
  }

  selectCompType(compType: string){
    this.compType = compType;
    this.onSelectCompType.emit(compType);
  }

}

<div class="sidebar">
    <ul>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_EPL}"
       (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_EPL)">{{sharedVar.COMP_HEADER_EPL}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_LALIGA}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_LALIGA)">{{sharedVar.COMP_HEADER_LALIGA}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_BUNDESLIGA}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_BUNDESLIGA)">{{sharedVar.COMP_HEADER_BUNDESLIGA}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_SERIE_A}" 
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_SERIE_A)">{{sharedVar.COMP_HEADER_SERIE_A}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_LIGUE_ONE}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_LIGUE_ONE)">{{sharedVar.COMP_HEADER_LIGUE_ONE}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_FA_CUP}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_FA_CUP)">{{sharedVar.COMP_HEADER_FA_CUP}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_EFL_CUP}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_EFL_CUP)">{{sharedVar.COMP_HEADER_EFL_CUP}}</li>
      <li class="sidebar-item" [ngClass]="{'highlightSideNav' : compType == sharedVar.API_SOURCE_COMP_TYPE_UCL}"
      (click)="selectCompType(sharedVar.API_SOURCE_COMP_TYPE_UCL)">{{sharedVar.COMP_HEADER_UCL}}</li>
    </ul>
</div>
