// oasisbet-frontend/src/app/views/c-main-menu/main-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { AuthService } from 'src/app/services/auth/auth.service';
import { SharedMethodsService } from 'src/app/services/shared-methods.service';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-main-menu',
  templateUrl: './main-menu.component.html',
  styleUrls: ['./main-menu.component.css']
})
export class MainMenuComponent implements OnInit {

  public spinme: string = 'none';

  public subscriptions: Subscription = new Subscription();

  constructor(public authService: AuthService,
    public sharedVar: SharedVarService,
    public sharedMethods: SharedMethodsService) { }

  ngOnInit(): void {
    this.subscriptions.add(
      this.sharedVar.currentSpinner.subscribe(status => this.spinme = status)
    );
  }

  logout(): void {
    this.authService.logout();
  }
}

<header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/odds" routerLinkActive="active">Odds</a>
          </li>
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/results" routerLinkActive="active">Results</a>
          </li>
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/account" routerLinkActive="active">Account</a>
          </li>
        </ul>
      </div>

      <div class="right-navbar" *ngIf="authService.isUserLoggedIn()">
        <ul class="navbar-nav">
          <li class="nav-item login-user-textbox">
            <span class="logged-in-text">LOGGED IN &nbsp; {{sharedVar.loginTimer}}</span>
            <i class="fa fa-user user-icon"></i>
            <a class="login-username-tag" routerLink="/account" routerLinkActive="active"> {{authService.getAuthenticationUser()}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link main-menu-link" (click)="logout()">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="cover-spin" [ngStyle]="{'display': spinme}"></div>
</header>

// oasisbet-react/src/MainMenu.jsx
import './MainMenu.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons/faUser';
import Button from 'react-bootstrap/Button';


export default function MainMenu(){
    return (
        <header>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link main-menu-link" routerLink="/odds" routerLinkActive="active">Odds</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link main-menu-link" routerLink="/results" routerLinkActive="active">Results</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link main-menu-link" routerLink="/account" routerLinkActive="active">Account</a>
                    </li>
                    </ul>
                </div>

                <div class="right-navbar">
                    <ul class="navbar-nav">
                        <li class="nav-item user-menu-display">
                            <span>LOGGED IN &nbsp;</span>
                            <Button type="button" variant="secondary" class="btn-logout">Logout</Button>
                            <FontAwesomeIcon icon={faUser} class="user-icon"/>
                            <a class="login-username-tag" routerLink="/account" routerLinkActive="active"> CHOONANN</a>
                        </li>
                        <li class="nav-item">
                            <span class="balance-textbox">Balance: $99.88</span>
                        </li>
                    </ul>
                </div>
            </nav>

            
        </header>
    );
}
