// oasisbet-react/src/component/common/dialog/ConfirmDialog.tsx
import React, { useState, useEffect } from 'react';
import './ConfirmDialog.css';
import SharedVarConstants from '../../../constants/SharedVarConstants.ts';
import { Card } from 'react-bootstrap';

interface ConfirmDialogProps {
    isOpen: boolean;
    onClose: (result?: string) => void;
    data: {
      title: string;
      type: string;
    };
}

const ConfirmDialog: React.FC<ConfirmDialogProps> = ({ isOpen, onClose, data }) => {
  const [dialogTitle, setDialogTitle] = useState('');
  const [dialogMessage, setDialogMessage] = useState('');

  useEffect(() => {
    if (isOpen) {
        setDialogTitle(data.title);
        setDialogMessage(retrieveDialogMessage(data.type));
    } 
    document.body.style.overflow = isOpen ? 'hidden' : 'auto';
  }, [isOpen, data]);

  const retrieveDialogMessage = (dialogType) => {
    switch (dialogType) {
      case SharedVarConstants.CREATE_USER_DIALOG_TYPE:
        return SharedVarConstants.CREATE_USER_DIALOG_MSG;
      case SharedVarConstants.CFM_DEPOSIT_DIALOG_TYPE:
        return SharedVarConstants.CFM_DEPOSIT_DIALOG_MSG;
      case SharedVarConstants.CFM_WITHDRAW_DIALOG_TYPE:
        return SharedVarConstants.CFM_WITHDRAW_DIALOG_MSG;
      case SharedVarConstants.CFM_CHANGE_LIMIT_DIALOG_TYPE:
        return SharedVarConstants.CFM_CHANGE_LIMIT_DIALOG_MSG;
      case SharedVarConstants.CFM_UPDATE_PW_DIALOG_TYPE:
        return SharedVarConstants.CFM_UPDATE_PW_DIALOG_MSG;
      case SharedVarConstants.CFM_UPDATE_ACC_DETAILS_DIALOG_TYPE:
        return SharedVarConstants.CFM_UPDATE_ACC_DETAILS_DIALOG_MSG;
      default:
        return '';
    }
  };

  const handleCancelClick = () => {
    onClose('cancel');
  };

  const handleConfirmClick = () => {
    onClose('confirm');
  };

  return (
    isOpen && (
        <div className="dialog-overlay">
            <Card className="card dialog">
                <Card.Header className="card-header dialog-header">
                    <h2>{dialogTitle}</h2>
                </Card.Header>
                <Card.Body className="card-body dialog-body">
                    <br></br>
                    <p>{dialogMessage}</p>
                    <div className="dialog-footer">
                        <button className="btn btn-danger btn-cancel" type="button" 
                            onClick={handleCancelClick}>
                            Cancel
                        </button>
                        <button className="btn btn-success btn-confirm-action" type="button" 
                            onClick={handleConfirmClick}>
                            Confirm
                        </button>
                    </div>
                </Card.Body>
            </Card>
        </div>
    )
  );
};

export default ConfirmDialog;

// oasisbet-frontend/src/app/common/confirm-dialog/confirm-dialog.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-confirm-dialog',
  templateUrl: './confirm-dialog.component.html',
  styleUrls: ['./confirm-dialog.component.css']
})
export class ConfirmDialogComponent implements OnInit {

  dialogTitle: string = '';
  dialogMessage: string = ''; 

  ngOnInit(): void {
    this.dialogTitle = this.data.title;
    this.dialogMessage = this.retrieveDialogMessage(this.data.type);
  }

  constructor(
    public sharedVarService: SharedVarService,
    public dialogRef: MatDialogRef<ConfirmDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any) {}

  onCancelClick(): void {
    this.dialogRef.close();
  }

  onConfirmClick(): void {
    this.dialogRef.close('confirm');
  }

  retrieveDialogMessage(dialogType: string){
    switch (dialogType) {
      case this.sharedVarService.CREATE_USER_DIALOG_TYPE:
        return this.sharedVarService.CREATE_USER_DIALOG_MSG;
      case this.sharedVarService.CFM_DEPOSIT_DIALOG_TYPE:
        return this.sharedVarService.CFM_DEPOSIT_DIALOG_MSG;
      case this.sharedVarService.CFM_WITHDRAW_DIALOG_TYPE:
        return this.sharedVarService.CFM_WITHDRAW_DIALOG_MSG;
      case this.sharedVarService.CFM_CHANGE_LIMIT_DIALOG_TYPE:
        return this.sharedVarService.CFM_CHANGE_LIMIT_DIALOG_MSG;
      case this.sharedVarService.CFM_UPDATE_PW_DIALOG_TYPE:
        return this.sharedVarService.CFM_UPDATE_PW_DIALOG_MSG;
      case this.sharedVarService.CFM_UPDATE_ACC_DETAILS_DIALOG_TYPE:
        return this.sharedVarService.CFM_UPDATE_ACC_DETAILS_DIALOG_MSG;
      default:
        return ''; 
    }
  }

}


<div class="card">
  <h1 class="card-header" cdkFocusInitial>
    {{dialogTitle}}
  </h1>
  <div class="card-body">
      <div class="row" align="center">
        <h4>{{dialogMessage}}</h4>
      </div>
      <div class="row justify-content-center">
        <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelClick()">
          Cancel
        </button>
        <button class="btn btn-success btn-confirm" type="button" (click)="onConfirmClick()">
          Confirm
        </button>
      </div>
  </div>
</div>
