// oasisbet-react/src/component/account/CreateUser.tsx
import React, { useState } from 'react';
import './CreateUser.css';
import { Card } from "react-bootstrap";
import SharedVarConstants from '../../constants/SharedVarConstants';
import ConfirmDialog from '../common/dialog/ConfirmDialog.tsx';
import { createUser } from '../../services/api/ApiService.js';
import { UserModel } from '../../model/UserModel.tsx';
import { CreateUserModel } from '../../model/CreateUserModel.tsx';
import { isEqualToOtherValue, isShorterThanMinLength, isLongerThanMaxLength, isNotEmpty, isOnlyContainsAlphaNumeric, isOnlyContainsNumeric, isValidEmail } from '../util/validation.js';
import { useNavigate } from 'react-router-dom';

const CreateUser = () => {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [cfmPassword, setCfmPassword] = useState('');
  const [email, setEmail] = useState('');
  const [contactNo, setContactNo] = useState('');
  const [errors, setErrors] = useState({
    username: '',
    password: '',
    cfmPassword: '',
    email: '',
    contactNo: ''
  });
  const [errorMsg, setErrorMsg] = useState('');
  const [isDialogOpen, setDialogOpen] = useState(false);
  const [dialogData, setDialogData] = useState({ title: '', type: '' });

  const handleValidation = (inputType) => {
    let validationErrors = {
      username: '',
      password: '',
      cfmPassword: '',
      email: '',
      contactNo: ''
    };

    if(inputType === 'username'){
      validationErrors.username = validateUsername(username);
    }
    
    if(inputType === 'password'){
      validationErrors.password = validatePassword(password);
    }
    
    if(inputType === 'cfmPassword'){
      validationErrors.cfmPassword = validateCfmPassword(cfmPassword);
    }

    if(inputType === 'email'){
      validationErrors.email = validateEmail(email);
    }
    
    if(inputType === 'contactNo'){
      validationErrors.contactNo = validateContactNo(contactNo);
    }

    setErrors(validationErrors);
  };

  const confirmClicked = () => {
      const validationErrors = {
        username: '',
        password: '',
        cfmPassword: '',
        email: '',
        contactNo: ''
      };
      validationErrors.username = validateUsername(username);
      validationErrors.password = validatePassword(password);
      validationErrors.cfmPassword = validateCfmPassword(cfmPassword);
      validationErrors.email = validateEmail(email);
      validationErrors.contactNo = validateContactNo(contactNo);
      setErrors(validationErrors);
      const checkValidation = Object.values(validationErrors).every(error => error === '');
    if (checkValidation) {
      console.log('Form is valid, submitting form to backend now');
      handleOpenDialog();
    } else {
      console.log('Form is invalid');
    }
  };

  const handleOpenDialog = () => {
    setDialogData({
      title: 'Confirm Create User?',
      type: SharedVarConstants.CREATE_USER_DIALOG_TYPE,
    });
    setDialogOpen(true);
  };

  const handleCloseDialog = async (result) => {
    setDialogOpen(false);
    if (result === 'confirm') {
      console.log('Confirmed!');
      const formDetails: UserModel = {
        id: -1,
        username: username,
        password: password,
        email: email,
        contactNo: contactNo,
        delInd: '',
        createdBy: '',
        createdDt: null
      };
      const request: CreateUserModel = {
        user: formDetails
      };

      try {
          const response = await createUser(request);
          if(response.statusCode !== 0){
            console.log("Error creating user, response:", response);
            setErrorMsg(response.resultMessage);
          } else {
            //create user success! sending resultMessage back to account login screen
            console.log("User created successfully:", response);
            navigate('/account');
            dispatch({ type: 'CREATE_USER', payload: response.resultMessage });
            setErrorMsg('');
          }
      } catch (error) {
          //TODO to change this error message to a generic error message shown as red banner
          console.error("Error creating user:", error);
          setErrorMsg("Failed to create user. Please try again.");
      }
    } else {
      console.log('Cancelled!');
    }
  };

  const handleOnBlurInput = (inputType) => (e) => {
    handleValidation(inputType);
  }

  const handleOnChangeInput = (inputType) => (e) => {
    if(inputType === 'username'){
      setUsername(e.target.value.toUpperCase());
    } else if(inputType === 'password'){
      setPassword(e.target.value);
    } else if(inputType === 'cfmPassword'){
      setCfmPassword(e.target.value);
    } else if(inputType === 'email'){
      setEmail(e.target.value.toUpperCase());
    } else if(inputType === 'contactNo'){
      setContactNo(e.target.value);
    }
    setErrors((prevState) => ({
      ...prevState, 
      [inputType]: ''
    }));
  }

  function validateUsername(username: string): string {
    if (!isNotEmpty(username)) {
      return 'This field is required';
    } else if (!isOnlyContainsAlphaNumeric(username)) {
      return 'Please enter only alphabet characters';
    } else if (isLongerThanMaxLength(username, 20)) {
      return 'Maximum length is 20 characters';
    } else if (isShorterThanMinLength(username, 5)) {
      return 'Minimum length is 5 characters';
    } else {
      return '';
    }
  }

  function validatePassword(password: string): string {
    if (!isNotEmpty(password)) {
      return 'This field is required';
    } else if (isLongerThanMaxLength(password, 20)) {
      return 'Maximum length is 20 characters';
    } else if (isShorterThanMinLength(password, 5)) {
      return 'Minimum length is 5 characters';
    } else {
      return '';
    }
  }
  
  function validateCfmPassword(cfmPassword: string): string {
    if (!isNotEmpty(cfmPassword)) {
      return 'This field is required';
    } else if (!isEqualToOtherValue(cfmPassword, password)) {
      return 'Passwords do not match';
    } else {
      return '';
    }
  }

  function validateEmail(email: string): string {
    if (!isNotEmpty(email)) {
      return 'This field is required';
    } else if (!isValidEmail(email)) {
      return 'Please enter a valid email address';
    } else if (isLongerThanMaxLength(100)) {
      return 'Maximum length is 100 characters';
    } else {
      return '';
    }
  }

  function validateContactNo(contactNo: string): string {
    if (!isNotEmpty(contactNo)) {
      return 'This field is required';
    } else if (!isOnlyContainsNumeric(contactNo)) {
      return 'Please enter only numeric characters';
    } else if (isLongerThanMaxLength(contactNo, 30)) {
      return 'Maximum length is 30 characters';
    } else {
      return '';
    }
  }

  return (
    <><div className="container">
      <br />
      {errorMsg && <div className="alert alert-danger col-md-6 offset-md-3"><b>Fail: </b>{errorMsg}</div>}
      <Card className="card col-md-6 offset-md-3">
        <Card.Header className="card-header">
          <h2>Create New Account</h2>
        </Card.Header>
        <Card.Body className="card-body d-flex flex-column align-items-center justify-content-center">
          <div className="container">
            <form>
              <div className="form-group form-row required col-md-8 align_cont_center">
                <label id="USERNAME_LABEL_1" htmlFor="username_0_Label" className={`control-label ${errors.username ? 'highlightLabel' : ''}`}>
                  <span id="USERNAME">User Name</span>
                  <span className="mandatory-label"></span>&nbsp;
                </label>
                <input
                  id="username_0"
                  type="text"
                  className="form-control allCaps"
                  value={username}
                  onBlur={handleOnBlurInput('username')}
                  onChange={handleOnChangeInput('username')}
                  name="username" />
                <label id="username_error_0" className={`error-text ${errors.username ? 'highlightLabel' : ''}`} htmlFor="name_0">
                  {errors.username}
                </label>
              </div>

              <br />

              <div className="form-group form-row required col-md-8 align_cont_center">
                <label id="PASSWORD_LABEL_1" htmlFor="password_0_Label" className={`control-label ${errors.password ? 'highlightLabel' : ''}`}>
                  <span id="PASSWORD">Password</span>
                  <span className="mandatory-label"></span>&nbsp;
                </label>
                <input
                  id="password_0"
                  type="password"
                  className="form-control allCaps"
                  value={password}
                  onBlur={handleOnBlurInput('password')}
                  onChange={handleOnChangeInput('password')}
                  name="password" />
                <label id="password_error_0" className={`error-text ${errors.password ? 'highlightLabel' : ''}`} htmlFor="password_0">
                  {errors.password}
                </label>
              </div>

              <br />

              <div className="form-group form-row required col-md-8 align_cont_center">
                <label id="CFMPASSWORD_LABEL_1" htmlFor="cfmPassword_0_Label" className={`control-label ${errors.cfmPassword ? 'highlightLabel' : ''}`}>
                  <span id="CFMPASSWORD">Confirm Password</span>
                  <span className="mandatory-label"></span>&nbsp;
                </label>
                <input
                  id="cfmPassword_0"
                  type="password"
                  className="form-control allCaps"
                  value={cfmPassword}
                  onBlur={handleOnBlurInput('cfmPassword')}
                  onChange={handleOnChangeInput('cfmPassword')}
                  name="cfmPassword" />
                <label id="cfmPassword_error_0" className={`error-text ${errors.cfmPassword ? 'highlightLabel' : ''}`} htmlFor="cfmPassword_0">
                  {errors.cfmPassword}
                </label>
              </div>

              <br />

              <div className="form-group form-row required col-md-8 align_cont_center">
                <label id="EMAIL_LABEL_1" htmlFor="email_0_Label" className={`control-label ${errors.email ? 'highlightLabel' : ''}`}>
                  <span id="EMAIL">Email</span>
                  <span className="mandatory-label"></span>&nbsp;
                </label>
                <input
                  id="email_0"
                  type="text"
                  className="form-control allCaps"
                  value={email}
                  onBlur={handleOnBlurInput('email')}
                  onChange={handleOnChangeInput('email')}
                  name="email" />
                <label id="email_error_0" className={`error-text ${errors.email ? 'highlightLabel' : ''}`} htmlFor="email_0">
                  {errors.email}
                </label>
              </div>

              <br />

              <div className="form-group form-row required col-md-8 align_cont_center">
                <label id="CONTACTNO_LABEL_1" htmlFor="contactNo_0_Label" className={`control-label ${errors.contactNo ? 'highlightLabel' : ''}`}>
                  <span id="CONTACTNO">Contact No</span>
                  <span className="mandatory-label"></span>&nbsp;
                </label>
                <input
                  id="contactNo_0"
                  type="text"
                  className="form-control allCaps"
                  value={contactNo}
                  onBlur={handleOnBlurInput('contactNo')}
                  onChange={handleOnChangeInput('contactNo')}
                  name="contactNo" />
                <label id="contactNo_error_0" className={`error-text ${errors.contactNo ? 'highlightLabel' : ''}`} htmlFor="contactNo_0">
                  {errors.contactNo}
                </label>
              </div>

              <div className="text-right">
                <button className="btn-register" type="button" onClick={confirmClicked}>
                  <span id="cfm">Register</span>
                </button>
              </div>
            </form>
          </div>
        </Card.Body>
      </Card>
      <br />
    </div>
    
      <ConfirmDialog
        isOpen={isDialogOpen}
        onClose={handleCloseDialog}
        data={dialogData} />
    </>
  );
};

export default CreateUser;


function dispatch(arg0: { type: string; payload: any; }) {
  throw new Error('Function not implemented.');
}

// oasisbet-frontend/src/app/account/create-user/create-user.component.ts
import { Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { FormGroup, AbstractControl } from '@angular/forms';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { take, finalize } from 'rxjs/operators';
import { ResponseModel } from 'src/app/model/response.model';
import { ApiService } from 'src/app/services/api/api.service';
import { SharedVarService } from 'src/app/services/shared-var.service';
import { ReactiveFormService } from 'src/app/services/reactive-form.service';
import { SharedMethodsService } from 'src/app/services/shared-methods.service';
import { MatDialog } from '@angular/material/dialog';
import { ConfirmDialogComponent } from 'src/app/common/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.css']
})
export class CreateUserComponent implements OnInit {

  public errorMsg: string = '';
  public createUserForm: FormGroup;

  subscriptions: Subscription = new Subscription();
  @ViewChild('confirmInputsModal', { static: true }) confirmInputsModal: TemplateRef<any>;

  constructor(public reactiveFormService: ReactiveFormService,
    public sharedVar: SharedVarService,
    public apiService: ApiService,
    public sharedMethods: SharedMethodsService,
    public dialog: MatDialog,
    private router: Router) { }

  ngOnInit(): void {
    this.createUserForm = this.initializeCreateUserForm();
    this.sharedMethods.initializeCreateUserModel();
  }

  initializeCreateUserForm(): FormGroup {
    const rfg =  this.reactiveFormService.initializeCreateUserForm();
    return rfg;
  }

  fieldIsInvalid(field: AbstractControl): boolean {
    return this.reactiveFormService.fieldIsInvalid(field);
  }

  backToHomeScreen(){
    this.router.navigate([''], { skipLocationChange: true });
  }

  confirmClicked(){
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      width: '400px',
      data: { message: 'Confirm Create User' }
    });
  
    dialogRef.afterClosed().subscribe(result => {
      if (result === 'confirm') {
        console.log("confirm create user");
        this.confirmCreateUser();
      } 
    });
  }

  confirmCreateUser(){
    if(this.createUserForm.valid){
      this.sharedVar.createUserModel.user.username = this.username?.value.toUpperCase();
      this.sharedVar.createUserModel.user.password = this.password?.value;
      this.sharedVar.createUserModel.user.contactNo = this.contactNo?.value;
      this.sharedVar.createUserModel.user.email = this.email?.value;
      console.log("create user success!");
      this.subscriptions.add(
        this.apiService.postCreateUser().subscribe( (resp: ResponseModel) => {
          if (resp.statusCode != 0) {
            this.errorMsg = resp.resultMessage;
            resp.resultMessage = "";
          } else {
            this.sharedVar.changeResponse(resp);
            this.backToHomeScreen();
          }
        } ,
          error => {
          this.sharedVar.changeException(error);
        })
      );
    } else{
      console.log("create user failed!");
      this.reactiveFormService.displayValidationErrors(this.createUserForm);
    }
  }

  get username() {
    return this.createUserForm.get('username');
  }

  get password() {
    return this.createUserForm.get('password');
  }

  get cfmPassword() {
    return this.createUserForm.get('cfmPassword');
  }

  get email() {
    return this.createUserForm.get('email');
  }

  get contactNo() {
    return this.createUserForm.get('contactNo');
  }

}

<div class="container">
  <br>
  <div class="card col-md-6 offset-md-3">
    <div class="alert alert-danger" *ngIf="errorMsg"><b>Fail: </b>{{errorMsg}}</div>
    <h1 class="d-inline card-header">Create New User</h1>
    <div class="card-body">
      <div class="container">
        <form [formGroup]="createUserForm">
          <div class="form-group form-row required col-md-8 align_cont_center">
            <label id="USERNAME_LABEL_1" for="username_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(username)}" class="control-label">
              <span id="USERNAME">User Name</span>
              <span class="mandatory-label"></span>&nbsp;
            </label>
            <input id="username_0" type="text" class="form-control allCaps" formControlName="username" name="username">
            <label id="username_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(username)}" class="error-text"
              for="name_0">
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(username)) == 'pattern'">Please enter only
                alphabet characters</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(username)) == 'maxlength'">Maximum length is 20
                characters</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(username)) == 'minlength'">Minimum length is 5
                characters</span>
              <span *ngIf="username.hasError('required') && !username.value && !username.pristine">This field is
                required</span>
            </label>
          </div>

          <br>

          <div class="form-group form-row required col-md-8 align_cont_center">
            <label id="PASSWORD_LABEL_1" for="password_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="control-label">
              <span id="PASSWORD">Password</span>
              <span class="mandatory-label"></span>&nbsp;
            </label>
            <input id="password_0" type="password" class="form-control allCaps" formControlName="password"
              name="password">
            <label id="password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="error-text"
              for="password_0">
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'maxlength'">Maximum length is 20
                characters</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'minlength'">Minimum length is 5
                characters</span>
              <span *ngIf="password.hasError('required') && !password.value && !password.pristine">This field is
                required</span>
            </label>
          </div>

          <br>

          <div class="form-group form-row required col-md-8 align_cont_center">
            <label id="CFMPASSWORD_LABEL_1" for="cfmPassword_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmPassword)}" class="control-label">
              <span id="CFMPASSWORD">Confirm Password</span>
              <span class="mandatory-label"></span>&nbsp;
            </label>
            <input id="cfmPassword_0" type="password" class="form-control allCaps" formControlName="cfmPassword"
              name="cfmPassword">
            <label id="cfmPassword_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmPassword)}"
              class="error-text" for="cfmPassword_0">
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmPassword)) == 'maxlength'">Maximum length is
                20
                characters</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmPassword)) == 'minlength'">Minimum length is
                5
                characters</span>
              <span *ngIf="cfmPassword.hasError('required') && !cfmPassword.value && !cfmPassword.pristine">This field
                is required</span>
              <span *ngIf="cfmPassword.hasError('passwordMismatch')">Passwords does not match</span>
            </label>
          </div>

          <br>

          <div class="form-group form-row required col-md-8 align_cont_center">
            <label id="EMAIL_LABEL_1" for="email_0_Label" [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}"
              class="control-label">
              <span id="EMAIL">Email</span>
              <span class="mandatory-label"></span>&nbsp;
            </label>
            <input id="email_0" type="text" class="form-control allCaps" formControlName="email" name="email">
            <label id="email_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}" class="error-text"
              for="email_0">
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'pattern'">Please enter a valid
                email address</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'maxlength'">Maximum length is 100
                characters</span>
              <span *ngIf="email.hasError('required') && !email.value && !email.pristine">This field is required</span>
            </label>
          </div>

          <br>

          <div class="form-group form-row required col-md-8 align_cont_center">
            <label id="CONTACTNO_LABEL_1" for="contactNo_0_Label"
              [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}" class="control-label">
              <span id="CONTACTNO">Contact No</span>
              <span class="mandatory-label"></span>&nbsp;
            </label>
            <input id="contactNo_0" type="text" class="form-control allCaps" formControlName="contactNo"
              name="contactNo">
            <label id="contactNo_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}" class="error-text"
              for="contactNo_0">
              <span *ngIf="contactNo.hasError('required') && !contactNo.value && !contactNo.pristine">This field is
                required</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'pattern'">Please enter only
                numeric characters</span>
              <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'maxlength'">Maximum length is
                30
                characters</span>
            </label>
          </div>



          <div class="text-right">
            <button class="btn btn-success btn-register" type="button" (click)="confirmClicked()">
              <span id="cfm">Register</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
