// oasisbet-react/src/component/account/LimitManagement.tsx
import React, { useEffect, useState } from "react";
import './LimitManagement.css';
import { Card, OverlayTrigger, ProgressBar, Tooltip } from "react-bootstrap";
import SharedVarConstants from "../../constants/SharedVarConstants.ts";
import { retrieveMtdAmounts } from "../../services/api/ApiService.ts";
import { useSessionStorage } from "../util/useSessionStorage.ts";

export default function LimitManagement(){
    const DEPOSIT = 'deposit';
    const BET = 'bet';

    const [accountDetails, setAccountDetails] = useSessionStorage(SharedVarConstants.ACCOUNT_DETAILS, {});
    const [mtdDepositAmt, setMtdDepositAmt] = useState('0.00');
    const [mtdBetAmt, setMtdBetAmt] = useState('0.00');
    const [depositProgress, setDepositProgress] = useState(0 as number);
    const [betProgress, setBetProgress] = useState(0 as number);
    const [password, setPassword] = useState('');
    const [depositErrorMsg, setDepositErrorMsg] = useState('');
    const [betErrorMsg, setBetErrorMsg] = useState('');

    const [selectedDepositOption, setSelectedDepositOption] = useState('300');
    const [selectedBetOption, setSelectedBetOption] = useState('100');

    const [selectedDepositAmt, setSelectedDepositAmt] = useState('300');
    const [selectedBetAmt, setSelectedBetAmt] = useState('100');

    const [isDepositAmtInputDisabled, setIsDepositAmtInputDisabled] = useState(true);
    const [isBetAmtInputDisabled, setIsBetAmtInputDisabled] = useState(true);

    const [successMsg, setSuccessMsg] = useState('');
    const [errorMsg, setErrorMsg] = useState('');
    
    useEffect(() => {
        console.log("accountDetails in Deposits: ", accountDetails);
        const { accId, depositLimit, betLimit } = accountDetails || {};

        retrieveAccDetails(depositLimit, betLimit, accId);

        setAccountDetails(accountDetails);
    }, [accountDetails, setAccountDetails]);

    const retrieveAccDetails = async (depositLimit: number, betLimit: number, accId: string) => {
        try {
            const response: any = await retrieveMtdAmounts(accId);
            const mtdDepositAmt = response.account.mtdDepositAmt;
            const mtdBetAmt = response.account.mtdBetAmount;
            const depositProgress = mtdDepositAmt ? (mtdDepositAmt/depositLimit) * 100 : 0;
            const betProgress = mtdBetAmt ? (mtdBetAmt/betLimit) * 100 : 0;

            setMtdDepositAmt(mtdDepositAmt != null ? mtdDepositAmt.toFixed(2).toString() : '0.00');
            setMtdBetAmt(mtdBetAmt != null ? mtdBetAmt.toFixed(2).toString() : '0.00');
            setDepositProgress(depositProgress);
            setBetProgress(betProgress);
        } catch (error) {
            //TODO to change this error message to a generic error message shown as red banner
            console.error("Error in retrieve MTD amounts:", error);
            setErrorMsg("Error in retrieving Account Details. Please try again.");
        }
    } 

    const handlePasswordChange = (e) => {
        setPassword(e.target.value);
    }

    const handleInputLimitChange = (e, type) => {
        const value = e.target.value;
        const isOtherSelected = value === 'other';
        const newValue = isOtherSelected ? '' : value;
    
        if (type === DEPOSIT) {
            const depositAmt = isOtherSelected ? '' : newValue;
            setSelectedDepositAmt(depositAmt);
            setSelectedDepositOption(newValue);
            setIsDepositAmtInputDisabled(!isOtherSelected);
            setDepositErrorMsg('');
        } else if (type === BET) {
            const betAmt = isOtherSelected ? '' : newValue;
            setSelectedBetAmt(betAmt);
            setSelectedBetOption(newValue);
            setIsBetAmtInputDisabled(!isOtherSelected);
            setBetErrorMsg('');
        }
    };

    const validateInput = (amount, type) => {
        const pattern = /^(0(\.\d{1,2})?|[1-9]\d{0,8}(\.\d{1,2})?)$/;
        let errorMsg = '';
    
        if (amount > 200000) {
            errorMsg = 'Maximum amount to set is $199999.99';
        } else if (!pattern.test(amount)) {
            errorMsg = 'Please enter correct format';
        }
    
        if (type === DEPOSIT) {
            setDepositErrorMsg(errorMsg);
        } else if (type === BET) {
            setBetErrorMsg(errorMsg);
        }
    
        return;
    };

    const onChangeInputAmount = (e, type) => {
        validateInput(e.target.value, type);
        if(type === DEPOSIT){
            setSelectedDepositAmt(e.target.value)
        } else if(type === BET){
            setSelectedBetAmt(e.target.value)
        }
    }
    
    const onCancel = () => {
        setSelectedDepositOption('300');
        setSelectedDepositAmt('300');
        setSelectedBetOption('100');
        setSelectedBetAmt('100');
        setPassword('');
        setIsDepositAmtInputDisabled(true);
        setIsBetAmtInputDisabled(true);
    }

    return (
        <div className="container-fluid">
            <br />
            {successMsg && <div className="alert alert-success col-md-6 offset-md-3"><b>Success: </b>{successMsg}</div>}
            {errorMsg && <div className="alert alert-danger col-md-6 offset-md-3"><b>Fail: </b>{errorMsg}</div>}
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Limit Management</h2>
                </Card.Header>
                <Card.Body className="card-body">
                    <form>
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">Deposited</label>
                            <div className="col-sm-6 col-md-6 progress-bar-section">
                            <OverlayTrigger 
                                placement="top"
                                overlay={
                                <Tooltip id={`tooltip-top`}>
                                    {'$' + mtdDepositAmt}
                                </Tooltip>
                                }
                            >
                                <ProgressBar now={depositProgress} />
                            </OverlayTrigger>
                            </div>
                            <label className="control-label col-sm-3 col-md-3 limit-right-section-label-width">Current Limit</label>
                        </div>
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">$0.00</label>
                            <div className="col-sm-6 col-md-6">
                                <span>{depositProgress}%</span>
                            </div>
                            <label className="control-label col-sm-3 col-md-3 limit-right-section-label-width">${accountDetails.depositLimit}</label>
                        </div>
                        <br />
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">Change Monthly Deposit Limit</label>
                            <div className="col-md-3">
                            <div className="dropdown-section">
                                <select id="depositLimitDropdown" className="limit-dropdown"
                                    value={selectedDepositOption || 'other'} onChange={(e) => handleInputLimitChange(e, DEPOSIT)}>
                                    <option value="300">$300</option>
                                    <option value="500">$500</option>
                                    <option value="1000">$1000</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                            </div>
                            <div className="col-md-3">
                            <div className="input-group">
                                <div className="input-group-prepend">
                                <span className="input-group-text">$</span>
                                </div>
                                <input type="text" className="form-control limit-left-section-selection-width no-spinner" 
                                id="deposit_limit_0" name="deposit_limit" 
                                value={selectedDepositAmt}
                                onChange={(e) => onChangeInputAmount(e, DEPOSIT)}
                                disabled={isDepositAmtInputDisabled} required />
                                <label id="input_error_0" className={`error-text ${depositErrorMsg ? 'highlightLabel' : ''}`} htmlFor="input_0">
                                    {depositErrorMsg}
                                </label>
                            </div>
                            </div>
                        </div>
                        <br />
                        <hr />
                        <br />
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">Bets</label>
                            <div className="col-sm-6 col-md-6 progress-bar-section">
                            <OverlayTrigger 
                                placement="top"
                                overlay={
                                <Tooltip id={`tooltip-top`}>
                                    {'$' + mtdBetAmt}
                                </Tooltip>
                                }
                            >
                                <ProgressBar now={betProgress} />
                            </OverlayTrigger>
                            </div>
                            <label className="control-label col-sm-3 col-md-3 limit-right-section-label-width">Current Limit</label>
                        </div>
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">$0.00</label>
                            <div className="col-sm-6 col-md-6">
                                <span>{betProgress}%</span>
                            </div>
                            <label className="control-label col-sm-3 col-md-3 limit-right-section-label-width">${accountDetails.betLimit}</label>
                        </div>
                        <br />
                        <div className="row">
                            <label className="control-label col-sm-3 col-md-3 limit-left-section-label-width">Change Monthly Betting Limit</label>
                            <div className="col-md-3">
                            <div className="dropdown-section">
                                <select id="betLimitDropdown" className="limit-dropdown"
                                    value={selectedBetOption || 'other' } onChange={(e) => handleInputLimitChange(e, BET)}>
                                    <option value="100">$100</option>
                                    <option value="200">$200</option>
                                    <option value="300">$300</option>
                                    <option value="400">$400</option>
                                    <option value="500">$500</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                            </div>
                            <div className="col-md-3">
                                <div className="input-group">
                                    <div className="input-group-prepend">
                                    <span className="input-group-text limit-section-selection-width">$</span>
                                    </div>
                                    <input type="text" className="form-control limit-section-selection-width no-spinner" 
                                    id="bet_limit_0" name="bet_limit" 
                                    value={selectedBetAmt} 
                                    onChange={(e) => onChangeInputAmount(e, BET)}
                                    disabled={isBetAmtInputDisabled} required />
                                    <label id="input_error_0" className={`error-text ${betErrorMsg ? 'highlightLabel' : ''}`} htmlFor="input_0">
                                        {betErrorMsg}
                                    </label>
                                </div>
                            </div>
                        </div>
                        <br />
                        <hr />
                        <br />
                        <div className="form-group row">
                            <label className="control-label col-sm-4 limit-left-section-label-width limit-acc-label-text">Enter OasisBet Account password</label>
                            <div className="col-md-3">
                            <input type="password" className="form-control limit-section-selection-width no-spinner" 
                            id="password_0" name="password" 
                            onChange={handlePasswordChange}
                            value={password}
                            required />
                            </div>
                        </div>
                        <hr />
                        <div className="dialog-actions">
                            <button className="btn btn-danger btn-cancel" type="button" onClick={onCancel}>
                                Cancel
                            </button>
                            <button className="btn btn-success btn-confirm-action" type="button">
                                Confirm
                            </button>
                        </div>
                        <br />
                    </form>
                </Card.Body> 
            </Card>
        </div>
    );
}

// oasisbet-frontend/src/app/account/limit-management/limit-management.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup } from '@angular/forms';
import { ReactiveFormService } from 'src/app/services/reactive-form.service';

@Component({
  selector: 'app-limit-management',
  templateUrl: './limit-management.component.html',
  styleUrls: ['./limit-management.component.css']
})
export class LimitManagementComponent implements OnInit {

  errorMsg : string = "";
  responseMsg: string = "";

  public limitMgmtForm: FormGroup;

  constructor(public reactiveFormService: ReactiveFormService) { }

  ngOnInit(): void {
    this.limitMgmtForm = this.reactiveFormService.initializeLimitMgmtFormControl();

    this.depositLimit.setValue(300);
    this.betLimit.setValue(100);
  }

  onChangesDepositLimit(depositLimitSelection: AbstractControl){
    if(depositLimitSelection.value != 'other'){
      this.depositLimit.disable();
      this.depositLimit.setValue(depositLimitSelection.value);
    } else {
      this.depositLimit.enable();
      this.depositLimit.setValue(null);
    }
  }

  onChangesBetLimit(betLimitSelection: AbstractControl){
    if(betLimitSelection.value != 'other'){
      this.betLimit.disable();
      this.betLimit.setValue(betLimitSelection.value);
    } else {
      this.betLimit.enable();
      this.betLimit.setValue(null);
    }
  }

  fieldIsInvalid(field: AbstractControl): boolean {
    return this.reactiveFormService.fieldIsInvalid(field);
  }

  onCancelSetLimit(){
    this.depositLimit.setValue(null);
    this.betLimit.setValue(null);
    this.password.setValue(null);
  }

  onConfirmSetLimit(){
    console.log(this.depositLimit.value);
    console.log(this.betLimit.value);
    this.errorMsg = "";
    this.responseMsg = "";
  }

  get depositLimitSelection() {
    return this.limitMgmtForm.get('depositLimitSelection');
  }

  get betLimitSelection() {
    return this.limitMgmtForm.get('betLimitSelection');
  }

  get password() {
    return this.limitMgmtForm.get('password');
  }

  get depositLimit() {
    return this.limitMgmtForm.get('depositLimit');
  }

  get betLimit() {
    return this.limitMgmtForm.get('betLimit');
  }
}

<div class="alert alert-success col-md-6 offset-md-3" *ngIf="responseMsg" ><b>Success: </b> {{responseMsg}}</div>
<div class="alert alert-danger col-md-6 offset-md-3" *ngIf="errorMsg"><b>Fail: </b>{{errorMsg}}</div>

<div class="card" >
    <div class="text-left">
        <h1 class="card-header">Limit Management</h1>
    </div>
    <div class="card-body">
        <form [formGroup]="limitMgmtForm">
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width">Deposited</label>
                <label class="control-label col-sm-6 col-md-6"> </label>
                <label class="control-label col-sm-3 col-md-3 limit-right-section-label-width">Current Limit</label>
            </div>
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width">$0.00</label>
                <div class="col-sm-6 col-md-6">
                    <mat-progress-bar [matTooltip]="'$' + mtdDepositAmt" matTooltipPosition="above" mode="determinate" [value]="depositProgress"></mat-progress-bar>
                    <span [matTooltip]="'$' + mtdDepositAmt">{{depositProgress | number:'1.0-2'}}%</span>
                </div>
                <label class="control-label col-sm-3 col-md-3 limit-right-section-label-width">${{currentDepositLimit | number: '1.2-2' }}</label>
            </div>
            <br>
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(depositLimit)}">Change Monthly Deposit Limit</label>
                <div class="col-md-3">
                    <div class="dropdown-section">
                        <select id="depositLimitDropdown"
                          class="form-control limit-dropdown"
                          (ngModelChange) = "onChangesDepositLimit(depositLimitSelection)"
                          formControlName="depositLimitSelection" >
                            <option value="300">$300</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="other">Other</option>
                        </select>
                        <span class="dropdown-icon"><i class="fas fa-angle-down"></i></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">$</span>
                        </div>
                    <input type="" class="form-control limit-left-section-selection-width no-spinner" id="deposit_limit_0" name="deposit_limit" 
                    formControlName="depositLimit" required>
                    </div>
                    <label id="deposit_limit_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(depositLimit)}" class="error-text"
                        for="deposit_limit_0">
                        <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(depositLimit)) == 'pattern'">Please enter correct format</span>
                        <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(depositLimit)) == 'maxAmount'">Maximum amount limit is $199999.99</span>
                        <span *ngIf="depositLimit.hasError('notZero')">Limit amount cannot be 0</span>
                        <span *ngIf="depositLimit.hasError('required') && !depositLimit.value && !depositLimit.pristine">This field is required</span>
                    </label>
                </div>
            </div>
            <br>
            <hr>
            <br>
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width">Bets</label>
                <label class="control-label col-sm-6 col-md-6"></label>
                <label class="control-label col-sm-3 col-md-3 limit-right-section-label-width">Current Limit</label>
            </div>
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width">$0.00</label>
                <div class="col-sm-6 col-md-6">
                    <mat-progress-bar [matTooltip]="'$' + mtdBetAmt" matTooltipPosition="above" mode="determinate" [value]="betProgress"></mat-progress-bar>
                    <span [matTooltip]="'$' + mtdBetAmt">{{betProgress | number:'1.0-2' }}%</span>
                </div>
                <label class="control-label col-sm-3 col-md-3 limit-right-section-label-width">${{currentBetLimit | number: '1.2-2' }}</label>
            </div>
            <br>
            <div class="row">
                <label class="control-label col-sm-3 col-md-3 limit-left-section-label-width" 
                [ngClass]="{'highlightLabel' : fieldIsInvalid(betLimit)}">Change Monthly Betting Limit</label>
                <div class="col-md-3">
                    <div class="dropdown-section">
                        <select id="betLimitDropdown"
                          class="form-control limit-dropdown"
                          (ngModelChange) = "onChangesBetLimit(betLimitSelection)"
                          formControlName="betLimitSelection">
                            <option value="100">$100</option>
                            <option value="200">$200</option>
                            <option value="300">$300</option>
                            <option value="400">$400</option>
                            <option value="500">$500</option>
                            <option value="other">Other</option>
                        </select>
                        <span class="dropdown-icon"><i class="fas fa-angle-down"></i></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text limit-section-selection-width">$</span>
                        </div>
                    <input type="" class="form-control limit-section-selection-width no-spinner" id="bet_limit_0" name="bet_limit" 
                    formControlName="betLimit" required>
                    </div>
                    <label id="bet_limit_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(betLimit)}" class="error-text"
                        for="bet_limit_0">
                        <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(betLimit)) == 'pattern'">Please enter correct format</span>
                        <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(betLimit)) == 'maxAmount'">Maximum amount limit is $199999.99</span>
                        <span *ngIf="betLimit.hasError('notZero')">Limit amount cannot be 0</span>
                        <span *ngIf="betLimit.hasError('required') && !betLimit.value && !betLimit.pristine">This field is required</span>
                    </label>
                </div>
            </div>
            <br>
            <hr>
            <br>
            <div class="form-group row">
                <label id="PASSWORD_LABEL_1" for="password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="control-label col-sm-4 limit-left-section-label-width limit-acc-label-text">
                <span id="PASSWORD">Enter OasisBet Account password</span>
                </label>
                <div class="col-md-3">
                <input type="password" class="form-control limit-section-selection-width no-spinner" formControlName="password" id="password_0" name="password" required>
                <label id="password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(password)}" class="error-text"
                    for="password_0">
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'maxlength'">Maximum length is 20
                    characters</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(password)) == 'minlength'">Minimum length is 5
                    characters</span>
                    <span *ngIf="password.hasError('required') && !password.value && !password.pristine">This field is
                    required</span>
                </label>
                </div>
            </div>
        </form>
        <hr>
        <div mat-dialog-actions align="end">
            <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelSetLimit()">
                Cancel
            </button>
            <button class="btn btn-success btn-confirm" type="button" (click)="confirmClicked()">
                Confirm
            </button>
        </div>
        <br>
    </div>
</div>
