// oasisbet-frontend/src/app/views/c-main-menu/main-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { AuthService } from 'src/app/services/auth/auth.service';
import { SharedMethodsService } from 'src/app/services/shared-methods.service';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-main-menu',
  templateUrl: './main-menu.component.html',
  styleUrls: ['./main-menu.component.css']
})
export class MainMenuComponent implements OnInit {

  public spinme: string = 'none';

  public subscriptions: Subscription = new Subscription();

  constructor(public authService: AuthService,
    public sharedVar: SharedVarService,
    public sharedMethods: SharedMethodsService) { }

  ngOnInit(): void {
    this.subscriptions.add(
      this.sharedVar.currentSpinner.subscribe(status => this.spinme = status)
    );
  }

  logout(): void {
    this.authService.logout();
    this.sharedMethods.stopLoginTimer()
  }
}

<header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/odds" routerLinkActive="active">Odds</a>
          </li>
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/results" routerLinkActive="active">Results</a>
          </li>
          <li class="nav-item">
            <a class="nav-link main-menu-link" routerLink="/account" routerLinkActive="active">Account</a>
          </li>
        </ul>
      </div>

      <div class="right-navbar" *ngIf="authService.isUserLoggedIn()">
        <ul class="navbar-nav">
          <li class="nav-item user-menu-display">
            <span>LOGGED IN &nbsp; {{sharedVar.loginTimer}}</span>
            <button type="button" class="btn btn-default btn-logout" (click)="logout()">Logout</button>
            <i class="fa fa-user user-icon"></i>
            <a class="login-username-tag" routerLink="/account" routerLinkActive="active"> {{authService.getAuthenticationUser()}}</a>
          </li>
          <li class="nav-item" *ngIf="authService.getRetrievedAccDetails().balance">
            <span class="balance-textbox">Balance: ${{authService.getRetrievedAccDetails().balance}}</span>
          </li>
        </ul>
      </div>

      <div class="right-navbar login-container" *ngIf="!authService.isUserLoggedIn()">
        <ul class="navbar-nav">
          <li class="nav-item">
            <form id="login-column">
              <div id="login-form" class="login-form-group-block">
                <div class="form-group login-form-group">
                  <input type="text" name="username" id="username" class="form-control" placeholder="Username">
                </div>
                <div class="form-group login-form-group">
                  <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                </div>
                <div class="form-group login-form-group">
                  <button id="authBtn" class="btn btn-success btn-login">Login</button>
                </div>
                <div class="form-group login-form-group">
                  <button id="signUpBtn" class="btn btn-success btn-signup">Sign Up</button>
                </div>
              </div>
            </form>
          </li>
        </ul>
      </div>
    </nav>
    <div id="cover-spin" [ngStyle]="{'display': spinme}"></div>
</header>

// oasisbet-react/src/component/MainMenu.tsx
import './MainMenu.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons/faUser';
import Button from 'react-bootstrap/Button';
import React, { useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';

export default function MainMenu(){

    const location = useLocation();

    const routeName = location.pathname.substring(1);

    console.log('Route parameters:', routeName);

    const usernameRef = useRef<HTMLInputElement>(null);
    const passwordRef = useRef<HTMLInputElement>(null);
    const [activeMenuButton, setActiveMenuButton] = useState(routeName);
    

    function handleOnChangeMenu(menu){
        setActiveMenuButton(menu);
    }

    function handleSubmitForm(event){
        event.preventDefault();
        console.log("form submission email: ", usernameRef.current?.value);
        console.log("form submission password: ", passwordRef.current?.value);
    }

    return (
        <header>
            <nav className="navbar navbar-expand-lg navbar-light">
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul className="navbar-nav">
                    <li className="nav-item">
                        <Link to="odds" style={{ textDecoration: 'none' }}>
                            <Button className={`nav-link main-menu-link ${activeMenuButton === 'odds' ? 'active' : ''}`}
                            onClick={() => handleOnChangeMenu('odds')}>
                                Odds
                            </Button>
                        </Link>
                    </li>
                    &nbsp;
                    <li className="nav-item">
                        <Link to="result" style={{ textDecoration: 'none' }}>
                            <Button className={`nav-link main-menu-link ${activeMenuButton === 'result' ? 'active' : ''}`}
                            onClick={() => handleOnChangeMenu('result')}>
                                Result
                            </Button>
                        </Link>
                    </li>
                    &nbsp;
                   <li className="nav-item">
                        <Link to="account" style={{ textDecoration: 'none' }}>
                            <Button className={`nav-link main-menu-link ${activeMenuButton === 'account' ? 'active' : ''}`}
                            onClick={() => handleOnChangeMenu('account')}>
                                Account
                            </Button>
                        </Link>
                    </li>
                    </ul>
                </div>

                {/* <div className="right-navbar">
                    <ul className="navbar-nav">
                        <li className="nav-item user-menu-display">
                            <span style={{borderRight: '1px solid #ccc'}}>LOGGED IN &nbsp;</span>
                            <Button type="button" variant="secondary" className="btn-logout">Logout</Button>
                            <FontAwesomeIcon icon={faUser} className="user-icon"/>
                            <span className="login-username-tag">&nbsp; CHOONANN</span>
                        </li>
                        <li className ="nav-item">
                            <span className="balance-textbox">Balance: $99.88</span>
                        </li>
                    </ul>
                </div> */}

                <div className="right-navbar login-container">
                    <ul className="navbar-nav">
                        <li className="nav-item">
                            <form id="login-column" onSubmit={handleSubmitForm}>
                                <div id="login-form" className="login-form-group-block">
                                    <div className="form-group login-form-group">
                                        <input
                                            type="text"
                                            name="username"
                                            id="username"
                                            ref={usernameRef}
                                            className="input-login"
                                            placeholder="Username"
                                        />
                                    </div>
                                    <div className="form-group login-form-group">
                                        <input
                                            type="password"
                                            name="password"
                                            id="password"
                                            ref={passwordRef}
                                            className="input-login"
                                            placeholder="Password"
                                        />
                                    </div>
                                    <div className="form-group login-form-group">
                                        <button type="submit" className="btn-login">
                                            Login
                                        </button>
                                    </div>
                                    <div className="form-group login-form-group">
                                        <button type="button" className="btn-signup">
                                            Sign Up
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
            </nav>

            
        </header>
    );
}
