// oasisbet-frontend/src/app/odds/odds-landing/odds-landing.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges, ViewChild } from '@angular/core';
import { SharedVarService } from 'src/app/services/shared-var.service';
import { BetEvent } from 'src/app/model/bet-event.model';
import { Subscription } from 'rxjs';
import { ApiService } from 'src/app/services/api/api.service';
import { take } from 'rxjs/operators';
import { H2HBetSelection } from 'src/app/model/h2h-bet-selection.model';
import { BetSlip } from 'src/app/model/bet-slip.model';

@Component({
  selector: 'app-odds-landing',
  templateUrl: './odds-landing.component.html',
  styleUrls: ['./odds-landing.component.css']
})
export class OddsLandingComponent implements OnInit  {

  public subscriptions: Subscription = new Subscription();

  compType: string = this.sharedVar.API_SOURCE_COMP_TYPE_EPL;
  competitionTypeHdr: string;
  public events : BetEvent[];
  public eventDates: string[];
  public eventsMap: Map<string, BetEvent[]> = new Map();

  @Output() betEventClicked = new EventEmitter<BetSlip[]>();

  public selectedBets : BetSlip[] = new Array();

  public responseMsg: string = '';

  constructor(public sharedVar: SharedVarService,
    public apiService: ApiService) {
    this.competitionTypeHdr = this.sharedVar.COMP_HEADER_EPL;
  }

  ngOnInit(): void {
    this.subscriptions.add(
        this.apiService.retrieveOdds(this.compType).subscribe((resp: any) => {
          this.events = resp.betEvent;

          //initiliase H2HBetSelection object and save to all events
          this.events.map(event => {
            const initBetSelection = new H2HBetSelection();
            event.betSelection = initBetSelection;
          });

          //convert json response from String to Date format
          this.events.map(event => event.startTime = new Date(event.startTime));

          //save unique event dates from all events retrieved
          this.eventDates = Array.from(new Set(this.events.map(event => {
            return event.startTime.toDateString();
          })));

          //save into a event map with unique event dates after retrival of events -> (Date string, BetEvents[])
          this.eventDates.forEach(dateString => {
            const eventsDetails = this.events.filter(event => event.startTime.toDateString() === dateString);
            this.eventsMap.set(dateString, eventsDetails);
          });
        } ,
          error => {
          console.log(error);
          this.sharedVar.changeException(error);
        }
      )
    );

    //get response success message after creating user
    this.subscriptions.add(
        this.sharedVar.responseSource.pipe(take(1))
        .subscribe(resp => {
          if(resp){
            this.responseMsg = resp.resultMessage;
            resp.resultMessage = "";
          }
        }
      )
    )
  }

  readCompType(competitionName: string){
    this.compType = competitionName;
    this.competitionTypeHdr = this.sharedVar.retrieveCompHdr(this.compType);
    this.ngOnInit();
  }

  selectBetSelection(event: BetEvent, selection: number){
    let addingBetSelection = false;
    let selectedTeam = "";
    let odds: number = 0;
    if(selection === 1){
      event.betSelection.homeSelected = !event.betSelection.homeSelected;
      addingBetSelection = event.betSelection.homeSelected;
      odds = event.h2hEventOdds.homeOdds;
      selectedTeam = event.teamsDetails.homeTeam;
    } else if(selection === 2){
      event.betSelection.drawSelected = !event.betSelection.drawSelected;
      addingBetSelection = event.betSelection.drawSelected;
      odds = event.h2hEventOdds.drawOdds;
      selectedTeam = "Draw";
    } else {
      event.betSelection.awaySelected = !event.betSelection.awaySelected;
      addingBetSelection = event.betSelection.awaySelected;
      odds = event.h2hEventOdds.awayOdds;
      selectedTeam = event.teamsDetails.awayTeam;
    }

    let betSlip = new BetSlip();
    betSlip.eventId = event.eventId;
    betSlip.eventDesc = event.eventDesc;
    betSlip.betTypeCd = 1;
    betSlip.betSelection = selection;
    betSlip.betSelectionName = selectedTeam;
    betSlip.odds = odds;

    if(addingBetSelection){
      this.selectedBets.push(betSlip);
      this.selectedBets = [...this.selectedBets];
    } else {
      this.selectedBets = this.selectedBets.filter(e => !(e.eventId === betSlip.eventId && e.betSelection === betSlip.betSelection));
    }
    this.betEventClicked.emit(this.selectedBets);
  }

  removeBet(removedBet: BetSlip){
    this.selectedBets = this.selectedBets.filter(e => !(e.eventId === removedBet.eventId && e.betSelection === removedBet.betSelection));
    const eventIdx = this.events.findIndex(e => e.eventId === removedBet.eventId);
    if (eventIdx !== -1) {
      const event = { ...this.events[eventIdx] };
      if(removedBet.betSelection === 1){
        event.betSelection.homeSelected = false;
      } else if(removedBet.betSelection === 2){
        event.betSelection.drawSelected = false;
      } else if(removedBet.betSelection === 3){
        event.betSelection.awaySelected = false;
      }
      this.events[eventIdx] = event;
    }
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <app-odds-side-nav (onSelectCompType)="readCompType($event)"></app-odds-side-nav>
        </div>

        <div class="col-md-8">
            <div class="container-fluid">
            <br>
                <div *ngIf="responseMsg" class="alert alert-success">
                    <b>Success: </b> {{responseMsg}}
                </div>
                <div class="card ">
                    <div class="text-left">
                        <h1 class="card-header">{{competitionTypeHdr}}</h1>
                    </div>
                    <div class="card-body">
                        <div class="container-fluid" *ngFor="let date of eventDates">
                          <h3 class="card-subtitle">{{date | date:'EEE, dd MMM yyyy' }}
                          </h3>
                          <table class="table" style="table-layout: fixed; width: 100%;">
                                <thead class= "table-header">
                                    <tr>
                                      <th style="width: 13%;">Time</th>
                                      <th style="width: 12%;">Event ID</th>
                                      <th style="width: 39%;">Event Description</th>
                                      <th style="width: 12%;">Home(1)</th>
                                      <th style="width: 12%;">Draw(X)</th>
                                      <th style="width: 12%;">Away(2)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr *ngFor="let event of eventsMap.get(date)">
                                        <td>{{event.startTime | date:'shortTime'}}</td>
                                        <td>{{event.eventId}}</td>
                                        <td>{{event.eventDesc}}</td>
                                        <td>
                                            <button type="button" class="btn btn-light" [ngClass]="{'selected': event.betSelection.homeSelected}"
                                            [disabled]="disableBets"
                                            (click)="selectBetSelection(event, sharedVar.BET_SELECTION_H2H_HOME)">
                                                <span class="bet-selection-text">01 | </span> &nbsp;
                                                {{ event.h2hEventOdds.homeOdds | number : '1.2-2' }}
                                            </button>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-light" [ngClass]="{'selected': event.betSelection.drawSelected}"
                                            [disabled]="disableBets"
                                            (click)="selectBetSelection(event, sharedVar.BET_SELECTION_H2H_DRAW)">
                                                <span class="bet-selection-text">02 | </span> &nbsp;
                                                {{ event.h2hEventOdds.drawOdds | number : '1.2-2' }}
                                            </button>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-light" [ngClass]="{'selected': event.betSelection.awaySelected}"
                                            [disabled]="disableBets"
                                            (click)="selectBetSelection(event, sharedVar.BET_SELECTION_H2H_AWAY)">
                                                <span class="bet-selection-text">03 | </span> &nbsp;
                                                {{ event.h2hEventOdds.awayOdds | number : '1.2-2' }}
                                            </button>
                                        </td>
                                    </tr>
                                    <tr *ngIf = '!events || events.length == 0'>
                                      <td class='text-center' colspan=12>
                                        No Event(s) Found.
                                      </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <app-odds-bet-slip [betSelections]="selectedBets" [initBetSlip]="betSlipSubject.asObservable()"
              [errorMsg]="maxBetMsg"
              (removedBetSelection)="removeBet($event)"
              (enableBets)="onEnableBets()"
              (betSelectionsChange)="updateBetSlip($event)" (removeAllBetSelections)="removeAllBets()">
            </app-odds-bet-slip>
        </div>
    </div>
</div>

// oasisbet-react/src/component/OddsLanding.tsx
import './OddsLanding.css';

import React, { useEffect, useRef, useState } from 'react';
import CompSideNav from './CompSideNav.tsx';
import { Button, Card, Table } from 'react-bootstrap';
import { BetEvent, BetSlip, H2HBetSelection } from '../constants/MockData.js';
import SharedVarConstants from '../constants/SharedVarConstants.js'; 
import OddsBetSlip from './OddsBetSlip.tsx';
import { useDispatch, useSelector } from 'react-redux';
import { fetchOdds } from '../services/api/ApiService.js';

export default function OddsLanding(){
    const dispatch = useDispatch();
    
    const betSlips = useSelector((state: any) => state.betSlip);
    const reducerAction = useSelector((state: any) => state.action);
    const [compType, setCompType] = useState(SharedVarConstants.API_SOURCE_COMP_TYPE_EPL);
    const [compTypeHdr, setCompTypeHdr] = useState(SharedVarConstants.COMP_HEADER_EPL);
    const [eventsMap, setEventsMap] = useState<Map<string, BetEvent[]>>(new Map());
    const [placeBetStatus, setPlaceBetStatus] = useState('I'); // I -> Init, C -> Confirm, D -> Done
    const selectedBetsRef = useRef([] as BetSlip[]);

    useEffect(() => {
        const fetchData = async (compType) => {
            try {
            const resp = await fetchOdds(compType);
            
            const betEvents = resp.betEvent;
            console.log("betEvents after retriving odds: ", betEvents);
    
            // Initialize H2HBetSelection object and save to all events
            const updatedEvents = betEvents.map(event => {
              const initBetSelection = new H2HBetSelection();
              event.betSelection = initBetSelection;
              return event;
            });
    
            // Convert startTime from string to Date format
            updatedEvents.forEach(event => event.startTime = new Date(event.startTime));
    
            // Record bet selection in current bet slip to match bet selection on screen
            const updatedSelectedBets = selectedBetsRef.current.map(betInBetSlip => {
              const betEvent = updatedEvents.find(event => event.eventId === betInBetSlip.eventId);
              if (betEvent) {
                if (betInBetSlip.betTypeCd === SharedVarConstants.BET_TYPE_CD_H2H && betInBetSlip.betSelection === SharedVarConstants.BET_SELECTION_H2H_HOME) {
                  betEvent.betSelection.homeSelected = true;
                } else if (betInBetSlip.betTypeCd === SharedVarConstants.BET_TYPE_CD_H2H && betInBetSlip.betSelection === SharedVarConstants.BET_SELECTION_H2H_DRAW) {
                  betEvent.betSelection.drawSelected = true;
                } else if (betInBetSlip.betTypeCd === SharedVarConstants.BET_TYPE_CD_H2H && betInBetSlip.betSelection === SharedVarConstants.BET_SELECTION_H2H_AWAY) {
                  betEvent.betSelection.awaySelected = true;
                }
              }
              return betInBetSlip;
            });

            selectedBetsRef.current = updatedSelectedBets;
    
            // Save unique event dates from all events retrieved
            const uniqueEventDates = Array.from(new Set(updatedEvents.map(event => event.startTime.toDateString())));
    
            // Save into an event map with unique event dates after retrieval of events -> (Date string, BetEvents[])
            const updatedEventsMap = new Map();
            uniqueEventDates.forEach(dateString => {
              const eventsDetails = updatedEvents.filter(event => event.startTime.toDateString() === dateString);
              updatedEventsMap.set(dateString, eventsDetails);
            });
            setEventsMap(updatedEventsMap);
    
            console.log("logging updatedEventsMap: ", updatedEventsMap);
            } catch (error) {
            // Handle error
            }
        };

        fetchData(compType);
    }, [compType]);

    useEffect(() => {
        return () => {
            dispatch({type: 'EMPTY_BET_SELECTION'});
        };
    }, [dispatch]);

    useEffect(() => {
        if(!betSlips || betSlips.length === 0){
            setPlaceBetStatus('I');
        }
        selectedBetsRef.current = betSlips;
    }, [betSlips]);

    useEffect(() => {
        if(reducerAction === 'CLEAR'){
            selectedBetsRef.current = [];
            setEventsMap((eventsMap) => {
                eventsMap.forEach((events) => {
                    events.forEach((betEvent) => {
                        betEvent.betSelection.homeSelected = false;
                        betEvent.betSelection.drawSelected = false;
                        betEvent.betSelection.awaySelected = false;
                    });
                });
                return new Map(eventsMap);
            });
        }
    }, [reducerAction]);

    const selectCompType = (newCompType) => {
        setCompTypeHdr(retrieveCompHdr(SharedVarConstants, newCompType));
        setCompType(newCompType);
    };

    console.log("eventsMap: ", eventsMap);
    const eventDates = eventsMap ? Array.from(eventsMap.keys()) : [];

    const formatDate = (dateString) => {
        const date = new Date(dateString);
        const options: Intl.DateTimeFormatOptions = { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' };
        return date.toLocaleDateString('en-US', options);
    };

    function selectBetSelection(index: number, date: any, selection: string) {
        const newBetEventsMap: any = new Map(eventsMap);

        const betEvents = newBetEventsMap.get(date);
        const betEvent = betEvents[index];

        if (!betEvent) {
            console.error('Invalid index or date');
            return;
        }

        let isRemoveBetSelection = false;
        let selectedTeam = "";
        let odds: number = 0;

        if (selection === SharedVarConstants.BET_SELECTION_H2H_HOME) {
            isRemoveBetSelection = betEvent.betSelection.homeSelected;
            betEvent.betSelection.homeSelected = !betEvent.betSelection.homeSelected;
            odds = betEvent.h2hEventOdds.homeOdds;
            selectedTeam = betEvent.teamsDetails.homeTeam;
        } else if (selection === SharedVarConstants.BET_SELECTION_H2H_DRAW) {
            isRemoveBetSelection = betEvent.betSelection.drawSelected;
            betEvent.betSelection.drawSelected = !betEvent.betSelection.drawSelected;
            odds = betEvent.h2hEventOdds.drawOdds;
            selectedTeam = SharedVarConstants.DRAW_RESULT;
        } else if (selection === SharedVarConstants.BET_SELECTION_H2H_AWAY) {
            isRemoveBetSelection = betEvent.betSelection.awaySelected;
            betEvent.betSelection.awaySelected = !betEvent.betSelection.awaySelected;
            odds = betEvent.h2hEventOdds.awayOdds;
            selectedTeam = betEvent.teamsDetails.awayTeam;
        }

        let betSlip = new BetSlip();
        betSlip.eventId = betEvent.eventId;
        betSlip.eventDesc = betEvent.eventDesc;
        betSlip.betTypeCd = SharedVarConstants.BET_TYPE_CD_H2H;
        betSlip.betSelection = selection;
        betSlip.betSelectionName = selectedTeam;
        betSlip.odds = odds;
        betSlip.startTime = betEvent.startTime;
        betSlip.compType = betEvent.compType;

        if (!isRemoveBetSelection) {
            selectedBetsRef.current.push(betSlip);
            selectedBetsRef.current = [...selectedBetsRef.current];
            dispatch({ type: 'ADD_BET_SELECTION', payload: selectedBetsRef.current });
        } else {
            selectedBetsRef.current = selectedBetsRef.current.filter(e => !(e.eventId === betSlip.eventId && e.betSelection === betSlip.betSelection));
            dispatch({ type: 'REMOVE_BET_SELECTION', payload: selectedBetsRef.current });
        }
        
        setPlaceBetStatus("I");
        newBetEventsMap.set(date, betEvents);
        setEventsMap(newBetEventsMap);
    }

    function handleBetSlipUpdate(deletedBetEvent){
        eventsMap.forEach(events => {
            const updatedEvent = events.find(event => event.eventId === deletedBetEvent.eventId) 
            const deletedBetEventSelection = deletedBetEvent.betSelection;
            if(updatedEvent && (deletedBetEventSelection === SharedVarConstants.BET_SELECTION_H2H_HOME)){
                updatedEvent.betSelection.homeSelected = !updatedEvent.betSelection.homeSelected;
            } else if(updatedEvent && (deletedBetEventSelection === SharedVarConstants.BET_SELECTION_H2H_DRAW)){
                updatedEvent.betSelection.drawSelected= !updatedEvent.betSelection.drawSelected;
            } else if(updatedEvent && (deletedBetEventSelection === SharedVarConstants.BET_SELECTION_H2H_AWAY)){
                updatedEvent.betSelection.awaySelected = !updatedEvent.betSelection.awaySelected;
            }
        })
        setEventsMap(new Map(eventsMap));
    }

    function handlePlaceBetStatusUpdate(status){
        setPlaceBetStatus(status);
    }

    return (
        <>
            <div className="container">
                <div className="row">
                    <div className="col-2">
                        <CompSideNav compType={compType} selectCompType={selectCompType}></CompSideNav>
                    </div>
                    <div className="col-8">
                        <div className="container-fluid">
                            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                                <Card.Header className="card-header">
                                    <h2>{compTypeHdr}</h2>
                                </Card.Header>
                                <Card.Body className="card-body">
                                    {eventDates.map((date, index) => (
                                        <div key={index}>
                                            <h3 className="card-subtitle">{formatDate(date)}</h3>
                                            <Table>
                                                <thead>
                                                    <tr>
                                                        <th style={{ width: '13%' }}>Time</th>
                                                        <th style={{ width: '12%' }}>Event ID</th>
                                                        <th style={{ width: '36%' }}>Event Description</th>
                                                        <th style={{ width: '13%' }}>Home (1)</th>
                                                        <th style={{ width: '13%' }}>Draw (X)</th>
                                                        <th style={{ width: '13%' }}>Away (2)</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {eventsMap?.get(date)?.map((event, index) => (
                                                        <tr key={index}>
                                                            <td>{new Date(event.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td>
                                                            <td>{event.eventId}</td>
                                                            <td>{event.eventDesc}</td>
                                                            <td>
                                                                <Button type="button" 
                                                                className={`btn ${event.betSelection.homeSelected ? 'selected' : ''}`}
                                                                variant="light"
                                                                onClick={() => selectBetSelection(index, date, SharedVarConstants.BET_SELECTION_H2H_HOME)}
                                                                disabled={placeBetStatus === 'C'}>
                                                                    <span className={`${event.betSelection.homeSelected ? 'selected' : 'bet-selection-text'}`}>
                                                                        01 | {parseFloat(event.h2hEventOdds.homeOdds).toFixed(2)}
                                                                    </span>
                                                                </Button>
                                                            </td>
                                                            <td>
                                                                <Button type="button" 
                                                                className={`btn ${event.betSelection.drawSelected ? 'selected' : ''}`}
                                                                variant="light"
                                                                onClick={() => selectBetSelection(index, date, SharedVarConstants.BET_SELECTION_H2H_DRAW)}
                                                                disabled={placeBetStatus === 'C'}>
                                                                    <span className={`${event.betSelection.drawSelected ? 'selected' : 'bet-selection-text'}`}>
                                                                        02 | {parseFloat(event.h2hEventOdds.drawOdds).toFixed(2)}
                                                                    </span>
                                                                </Button>
                                                            </td>
                                                            <td>
                                                                <Button type="button" 
                                                                className={`btn ${event.betSelection.awaySelected ? 'selected' : ''}`}
                                                                variant="light"
                                                                onClick={() => selectBetSelection(index, date, SharedVarConstants.BET_SELECTION_H2H_AWAY)}
                                                                disabled={placeBetStatus === 'C'}>
                                                                    <span className={`${event.betSelection.awaySelected ? 'selected' : 'bet-selection-text'}`}>
                                                                        03 | {parseFloat(event.h2hEventOdds.awayOdds).toFixed(2)}
                                                                    </span>
                                                                </Button>
                                                            </td>
                                                        </tr>
                                                    ))}
                                                </tbody>
                                            </Table>
                                        </div>
                                    ))}
                                    {
                                        (!eventsMap || eventsMap.size === 0) &&
                                        <div className="container-fluid text-center">
                                            <span>No Event(s) Found.</span>
                                        </div>
                                    }
                                </Card.Body>
                                
                            </Card>
                            
                        </div>
                    </div>
                    <div className="col-2">
                        <OddsBetSlip onBetSlipUpdate={handleBetSlipUpdate} onPlaceBetStatusUpdate={handlePlaceBetStatusUpdate} placeBetStatus={placeBetStatus}/>
                    </div>
                </div>
            </div>
        </>
    );
}

function retrieveCompHdr(sharedVar, newCompType): string {
    switch(newCompType) { 
        case sharedVar.API_SOURCE_COMP_TYPE_EPL: { 
            return sharedVar.COMP_HEADER_EPL; 
        } 
        case sharedVar.API_SOURCE_COMP_TYPE_LALIGA: { 
            return sharedVar.COMP_HEADER_LALIGA; 
        } 
        case sharedVar.API_SOURCE_COMP_TYPE_BUNDESLIGA: {
            return sharedVar.COMP_HEADER_BUNDESLIGA; 
        }
        case sharedVar.API_SOURCE_COMP_TYPE_SERIE_A: {
            return sharedVar.COMP_HEADER_SERIE_A; 
        }
        case sharedVar.API_SOURCE_COMP_TYPE_LIGUE_ONE: {
            return sharedVar.COMP_HEADER_LIGUE_ONE; 
        }
        case sharedVar.API_SOURCE_COMP_TYPE_FA_CUP: {
            return sharedVar.COMP_HEADER_FA_CUP; 
        }
        case sharedVar.API_SOURCE_COMP_TYPE_EFL_CUP: {
            return sharedVar.COMP_HEADER_EFL_CUP; 
        }
        case sharedVar.API_SOURCE_COMP_TYPE_UCL: {
            return sharedVar.COMP_HEADER_UCL; 
        }
        default: {
            return '';
        }
    }
}
