// oasisbet-frontend/src/app/odds/odds-bet-slip/odds-bet-slip.component.ts
import { Component, Input, OnInit, SimpleChanges } from '@angular/core';
import { BetEvent } from 'src/app/model/bet-event.model';
import { BetSlip } from 'src/app/model/bet-slip.model';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-odds-bet-slip',
  templateUrl: './odds-bet-slip.component.html',
  styleUrls: ['./odds-bet-slip.component.css']
})
export class OddsBetSlipComponent implements OnInit {
  public showSinglesSelection: boolean = true;
  public showMultiplesSelection: boolean = true;
  public totalStake: number = 0;
  public placedBetConfirmFlag: boolean = false;

  @Input() betSelections: BetSlip[];
  

  constructor(public sharedVar: SharedVarService) { }

  ngOnInit(): void {
  }
  
  ngOnChanges() {
      // Handle changes to selectedEvents and update the displayed selection
  }

  toggleSelection(selectionType: string): void {
    if (selectionType === 'singles') {
      this.showSinglesSelection = !this.showSinglesSelection;
    } else if (selectionType === 'multiples') {
      this.showMultiplesSelection = !this.showMultiplesSelection;
    }
  }

  onDeleteBetSelection(betSelection: BetSlip){
    this.betSelections = this.betSelections.filter(e => !(e.eventId === betSelection.eventId && e.betSelection === betSelection.betSelection));
  }

  onBetAmountChange(betSlipItem: BetSlip, betAmount: string) {
    const regex = /^(?!0\d)[1-9]\d{0,3}$/;
    if(regex.test(betAmount)){
      betSlipItem.betAmount = parseFloat(Number(betAmount).toFixed(2));
      betSlipItem.potentialPayout = parseFloat((betSlipItem.betAmount * betSlipItem.odds).toFixed(2));
    } else {
      betSlipItem.betAmount = 0;
      betSlipItem.potentialPayout = 0;
    }

    console.log(this.betSelections);
    this.totalStake = 0;
    this.betSelections.forEach(selection => this.totalStake =  this.totalStake + selection.betAmount);
  }

  onPlaceBets(){
    this.betSelections = this.betSelections.filter(e => e.betAmount !== 0 && e.potentialPayout !== 0);
    this.placedBetConfirmFlag = true;
  }

  onCancelPlaceBets(){
    this.betSelections.forEach(selection => {
      selection.betAmount = 0;
      selection.potentialPayout = 0;
    });
    this.totalStake = 0;
    this.placedBetConfirmFlag = false;
    
  }

  onConfirmPlaceBets(){
    //call backend api here to place bet
    this.placedBetConfirmFlag = false;
  }

}

<div class="bet-slip">
    <h2 class="bet-slip-header">Bet Slip</h2>
    
    <div class="alert alert-success" *ngIf="responseMsg" ><b>Success: </b> {{responseMsg}}</div>
    <div class="alert alert-danger" *ngIf="errorMsg"><b>Fail: </b>{{errorMsg}}</div>
    <div *ngIf="betSelections && betSelections.length > 0">
      <div class="header-panel">
        <h3 class="panel-header" (click)="toggleSelection('singles')">Singles<span class="dropdown-icon" ><i class="fas fa-angle-down"></i></span></h3>
        <div class="selections" *ngIf="showSinglesSelection">
          <div class="bet-slip-container" *ngFor="let betSelection of betSelections">
            <div class="container" *ngIf="!placedBetConfirmFlag || (betSelection.potentialPayout != 0 && placedBetConfirmFlag)">
              <div class="row">
                <div class="col-md-9">
                  <p class="event-description">{{ betSelection.eventDesc }}</p>
                  <p class="bet-type">{{ sharedVar.mapBetTypeCd(betSelection.betTypeCd) }}</p>
                  <p class="bet-selection">{{ betSelection.betSelectionName }} @ {{ betSelection.odds }}</p>
                </div>
                <div class="col-md-3">
                  <p class="delete-icon" (click)="onDeleteBetSelection(betSelection)">&#10005;</p>
                  <span class="bet-amount-input">
                    $<input #betAmountInput type="text" class="form-control" autocomplete="off" maxlength="7" inputmode="numeric" 
                    [value]="betSelection.betAmount"
                    *ngIf = "!placedBetConfirmFlag"
                    (input)="onBetAmountChange(betSelection, betAmountInput.value)">
                    <span *ngIf = "(betSelection.potentialPayout != 0 && placedBetConfirmFlag)">{{betSelection.betAmount | number : '1.2-2'}}</span>
                  </span>
                </div>
                <hr>
              </div>
              <div class="row">
                <p class="potential-payout-text">Potential Payout: ${{ betSelection.potentialPayout | number : '1.2-2' }}</p>
              </div>
            </div>
            <br>
          </div>

        </div>
      </div>
      <div class="total-stake-panel">
        <span class="total-stake-section">Total Stake: ${{totalStake}}</span>
      </div>
      <button class="btn btn-success btn-place-bet" *ngIf="!placedBetConfirmFlag" type="button" (click)="onPlaceBets()" [disabled]="!totalStake || totalStake === 0">
        Place Bet
      </button>
      <div class="row" *ngIf="placedBetConfirmFlag">
        <div class="col-md-6 d-flex justify-content-center">
          <button class="btn btn-success btn-decline" *ngIf="placedBetConfirmFlag" type="button" (click)="onCancelPlaceBets()">
            Decline
          </button>
        </div>
        <div class="col-md-6 d-flex justify-content-center">
          <button class="btn btn-success btn-confirm" *ngIf="placedBetConfirmFlag" type="button" (click)="onFinalConfirmPlaceBets()">
            Confirm
          </button>
        </div>
      </div>
    </div>

    <div class="empty-bet-slip" *ngIf="!betSelections || betSelections.length == 0">
        <p>Your bet slip is empty.</p>
    </div>
    
    
    <!-- <div class="header-panel" (click)="toggleSelection('multiples')">
      <h3 class="panel-header">Multiples<span class="dropdown-icon"><i class="fas fa-angle-down"></i></span></h3>
      <div class="selections" *ngIf="showMultiplesSelection">
        <p>Multiple Bet Selection</p>
      </div>
    </div>  -->
</div>

// oasisbet-react/src/component/OddsBetSlip.tsx
import React, { useEffect, useState } from "react";
import './OddsBetSlip.css';
import { faAngleDown } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useSelector } from "react-redux";

export default function OddsBetSlip(){
    const betEvents = useSelector((state: any) => state.betSlip);
    const [betSlipDisplay, setBetSlipDisplay] = useState([]) as any;
    const [showSingles, setShowSingles] = useState(true);

    useEffect(() => {
        console.log("betEvent: ", betEvents);
        setBetSlipDisplay(betEvents);
    }, [betEvents]);

    function handleClickSingles(event): void {
        setShowSingles(prevState => !prevState);
    }

    function handleOnDelete(betEvent): void {
        let updateBetEvents = [...betSlipDisplay];
        updateBetEvents = updateBetEvents.filter(e => !(e.eventId === betEvent.eventId));
        setBetSlipDisplay(updateBetEvents);
        //update reducer to remove betevents here
    }

    return (
        betSlipDisplay.length > 0 && 
        <div className="bet-slip">
            <h2 className="bet-slip-header">Bet Slip</h2>
            <div className="header-panel">
                <h3 className="panel-header" onClick={handleClickSingles}>Singles
                    <span className="dropdown-icon">
                        <FontAwesomeIcon icon={faAngleDown} />
                    </span>
                </h3>
                <br />
                {showSingles && 
                    <div className="selections">
                        <div className="bet-slip-container">
                            <div className="container">
                                {betSlipDisplay.map(betEvent => {
                                    return (
                                        <div key={betEvent.eventId + '_' + betEvent.betSelection}>
                                            <div className="row">
                                                <div className="col-md-10">
                                                    <p className="event-description">{betEvent.eventDesc}</p>
                                                </div>
                                                <div className="col-md-2" onClick={() => handleOnDelete(betEvent)}>
                                                    <p className="delete-icon">&#10005;</p>
                                                </div>
                                            </div>
                                            <div className="row">
                                                <p className="bet-type">1X2</p>
                                            </div>
                                            <div className="row">
                                                <div className="col-md-8">
                                                    <p className="bet-selection">{betEvent.betSelectionName} @ {betEvent.odds}</p>
                                                </div>    
                                                <div className="col-md-4">
                                                    <span className="bet-amount-input">
                                                        $<input type="text" maxLength={7} inputMode="numeric" />
                                                    </span>
                                                </div>    
                                            </div>
                                        </div>
                                    )
                                })}
                                <hr />
                                <div className="row">
                                    <p className="potential-payout-text">Potential Payout: $10.06</p>
                                </div>
                            </div>
                            <br/>
                        </div>
                    </div>
                }

                <div className="total-stake-panel">
                    <span className="total-stake-section">Total Stake: $2</span>
                </div>
                <button className="btn btn-success btn-place-bet" type="button">
                    Place Bet
                </button>
                <div className="row">
                    <div className="col-md-6 d-flex justify-content-center">
                        <button className="btn btn-success btn-decline" type="button">
                            Decline
                        </button>
                    </div>
                    <div className="col-md-6 d-flex justify-content-center">
                        <button className="btn btn-success btn-confirm" type="button">
                            Confirm
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
