// oasisbet-frontend/src/app/account/account-update/account-update/account-update.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-account-update',
  templateUrl: './account-update.component.html',
  styleUrls: ['./account-update.component.css']
})
export class AccountUpdateComponent implements OnInit {

  public errorMsg: string;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="alert alert-success" *ngIf="responseMsg"><b>Success: </b> {{responseMsg}}</div>
<div class="alert alert-danger" *ngIf="errorMsg"> <b>Fail: </b> {{errorMsg}}</div>
<div class="card ">
  <div class="text-left">
    <h1 class="card-header">Account Update</h1>
  </div>
  <div class="card-body">
    <hr>
      <mat-tab-group animationDuration="0ms">
        <mat-tab label="Contact Info">
          <br>
          <form [formGroup]="updateAccDetailsForm">
            <div class="form-group row mx-0">
              <label id="ACCOUNT_NO_LABEL" for="account_no_0_Label"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="ACCOUNT_NO">ACCOUNT NO.</span>
              </label>
              <label id="ACCOUNT_NO_INPUT" for="account_no_0_input"
                class="control-label col-sm-4 password-acc-label-text">
                <span id="ACCOUNT_NO"><b>{{accountId}}</b></span>
              </label>
            </div>
            <hr>
            <div class="form-group row mx-0">
              <label id="EMAIL_LABEL" for="email_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="EMAIL">Email:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="text" class="form-control password-section-selection-width no-spinner" formControlName="email"
                    id="email_0" name="email" required>
                </div>
                  <label id="email_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}" class="error-text"
                    for="email_0">
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'pattern'">Please enter a valid
                      email address</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'maxlength'">Maximum length is 100
                      characters</span>
                    <span *ngIf="email.hasError('required') && !email.value && !email.pristine">This field is required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="CONTACT_NO_LABEL" for="contact_no_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="CONTACT_NO">Contact No:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="text" class="form-control password-section-selection-width no-spinner" formControlName="contactNo"
                    id="contact_no_0" name="contactNo" required>
                </div>
                  <label id="contact_no_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}" class="error-text"
                    for="contact_no_0">
                    <span *ngIf="contactNo.hasError('required') && !contactNo.value && !contactNo.pristine">This field is
                      required</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'pattern'">Please enter only
                      numeric characters</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'maxlength'">Maximum length is
                      30 characters</span>
                  </label>
              </div>
            </div>
          </form>
        </mat-tab>
        <mat-tab label="Login information">
          <br>
          <form [formGroup]="updateLoginForm">
            <div class="form-group row mx-0">
              <label id="OLD_PASSWORD_LABEL" for="old_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(oldPassword)}"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="OLD_PASSWORD">Current Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control password-section-selection-width no-spinner" formControlName="oldPassword"
                    id="old_password_0" name="old_password" required>
                </div>
                  <label id="old_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(oldPassword)}" class="error-text"
                    for="old_password_0">
                    <span *ngIf="oldPassword.hasError('required') && !oldPassword.value && !oldPassword.pristine">This field is
                      required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="NEW_PASSWORD_LABEL" for="new_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(newPassword)}"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="NEW_PASSWORD">New Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control password-section-selection-width no-spinner" formControlName="newPassword"
                    id="new_password_0" name="new_password" required>
                </div>
                  <label id="new_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(newPassword)}" class="error-text"
                    for="new_password_0">
                  <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(newPassword)) == 'maxlength'">Maximum length is
                    20
                    characters</span>
                  <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(newPassword)) == 'minlength'">Minimum length is 5
                    characters</span>
                  <span *ngIf="newPassword.hasError('required') && !newPassword.value && !newPassword.pristine">This field is
                    required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="CFM_NEW_PASSWORD_LABEL" for="cfm_new_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmNewPassword)}"
                class="control-label col-sm-4 password-section-label-width password-acc-label-text">
                <span id="CFM_NEW_PASSWORD">Confirm New Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control password-section-selection-width no-spinner" formControlName="cfmNewPassword"
                      id="cfm_new_password_0" name="cfm_new_password" required>
                </div>
                  <label id="cfm_new_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmNewPassword)}" class="error-text"
                    for="cfm_new_password_0">
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmNewPassword)) == 'maxlength'">Maximum length
                      is 20
                      characters</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmNewPassword)) == 'minlength'">Minimum length
                      is 5
                      characters</span>
                    <span *ngIf="cfmNewPassword.hasError('required') && !cfmNewPassword.value && !cfmNewPassword.pristine">This
                      field is
                      required</span>
                    <span *ngIf="cfmNewPassword.hasError('passwordMismatch')">Passwords does not match</span>
                  </label>
              </div>
            </div>
          </form>
        </mat-tab>
      </mat-tab-group>
    <br>
    <hr>
    <div mat-dialog-actions align="end">
      <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelUpdate()">
          Cancel
      </button>
      <button class="btn btn-success btn-confirm" type="button" (click)="confirmClicked()">
          Confirm
      </button>
    </div>
    <br>
  </div>
</div>

// oasisbet-react/src/component/account/AccountUpdate.tsx
import React from "react";
import './AccountUpdate.css';
import { Card, Tab, Tabs } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPencil } from "@fortawesome/free-solid-svg-icons";

export default function AccountUpdate(){

    return (
        <div className="container-fluid">
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Account Update</h2>
                </Card.Header>
                <Card.Body className="card-body">
                <hr />
                <br />
                    <Tabs
                        defaultActiveKey="contact"
                        id="account-update-tab"
                        className="account-update-parent-tab-modal mb-3"
                        >
                        <Tab eventKey="contact" title="Contact Info">
                            <form>
                                <div className="form-group row mx-0">
                                    <label
                                    id="ACCOUNT_NO_LABEL"
                                    htmlFor="account_no_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="ACCOUNT_NO">ACCOUNT NO.</span>
                                    </label>
                                    <label
                                    id="ACCOUNT_NO_INPUT"
                                    htmlFor="account_no_0_input"
                                    className="control-label col-sm-4 acc-update-label-text"
                                    >
                                    <span id="ACCOUNT_NO">{1000001}</span>
                                    </label>
                                </div>
                                <hr />
                                <div className="form-group row mx-0">
                                    <label
                                    id="EMAIL_LABEL"
                                    htmlFor="email_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="EMAIL">Email:</span>
                                    </label>
                                    <div className="col-sm-4">
                                    <div className="input-group">
                                        <div className="input-group-prepend"></div>
                                        <input
                                        type="text"
                                        className="form-control acc-update-section-selection-width no-spinner"
                                        id="email_0"
                                        name="email"
                                        required
                                        />
                                        &nbsp;
                                        <div className="input-group-append">
                                        <button className="btn btn-outline-secondary btn-pencil" type="button">
                                            <FontAwesomeIcon icon={faPencil} className="pencil-icon"/>
                                        </button>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                                <div className="form-group row mx-0">
                                    <label
                                    id="CONTACT_NO_LABEL"
                                    htmlFor="contact_no_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="CONTACT_NO">Contact No:</span>
                                    </label>
                                    <div className="col-sm-4">
                                        <div className="input-group">
                                            <div className="input-group-prepend"></div>
                                            <input
                                            type="text"
                                            className="form-control acc-update-section-selection-width no-spinner"
                                            id="contact_no_0"
                                            name="contactNo"
                                            required
                                            />
                                            &nbsp;
                                            <div className="input-group-append">
                                            <button className="btn btn-outline-secondary btn-pencil" type="button">
                                                <FontAwesomeIcon icon={faPencil}/>
                                            </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <hr />
                            <div className="d-flex justify-content-end">
                            <button className="btn btn-danger btn-cancel" type="button">
                                Cancel
                            </button>
                            <button className="btn btn-success btn-confirm" type="button">
                                Confirm
                            </button>
                            </div>
                            <br />
                        </Tab>
                        <Tab eventKey="login" title="Login Info">
                        <form>
                            <div className="form-group row mx-0">
                                <label
                                id="OLD_PASSWORD_LABEL"
                                htmlFor="old_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="OLD_PASSWORD">Current Password:</span>
                                </label>
                                <div className="col-sm-4">
                                <div className="input-group">
                                    <div className="input-group-prepend"></div>
                                    <input
                                    type="password"
                                    className="form-control acc-update-section-selection-width no-spinner"
                                    id="old_password_0"
                                    name="old_password"
                                    required
                                    />
                                </div>
                                </div>
                            </div>
                            <div className="form-group row mx-0">
                                <label
                                id="NEW_PASSWORD_LABEL"
                                htmlFor="new_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="NEW_PASSWORD">New Password:</span>
                                </label>
                                <div className="col-sm-4">
                                <div className="input-group">
                                    <div className="input-group-prepend"></div>
                                    <input
                                    type="password"
                                    className="form-control acc-update-section-selection-width no-spinner"
                                    id="new_password_0"
                                    name="new_password"
                                    required
                                    />
                                </div>
                                </div>
                            </div>
                            <div className="form-group row mx-0">
                                <label
                                id="CFM_NEW_PASSWORD_LABEL"
                                htmlFor="cfm_new_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="CFM_NEW_PASSWORD">Confirm New Password:</span>
                                </label>
                                <div className="col-sm-4">
                                <div className="input-group">
                                    <div className="input-group-prepend"></div>
                                    <input
                                    type="password"
                                    className="form-control acc-update-section-selection-width no-spinner"
                                    id="cfm_new_password_0"
                                    name="cfm_new_password"
                                    required
                                    />
                                </div>
                                </div>
                            </div>
                        </form>
                            <hr />
                            <div className="d-flex justify-content-end">
                            <button className="btn btn-danger btn-cancel" type="button">
                                Cancel
                            </button>
                            <button className="btn btn-success btn-confirm" type="button">
                                Confirm
                            </button>
                            </div>
                            <br />
                        </Tab>
                    </Tabs>
                </Card.Body> 
            </Card>
        </div>
    );
}
