// oasisbet-frontend/src/app/account/account-update/account-update.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormGroup } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { Subscription } from 'rxjs';
import { finalize, take } from 'rxjs/operators';
import { ConfirmDialogComponent } from 'src/app/common/confirm-dialog/confirm-dialog.component';
import { AccountDetailsModel } from 'src/app/model/account-details.model';
import { AccountModel } from 'src/app/model/account.model';
import { PersonalDetailsModel } from 'src/app/model/personal-details.model';
import { ApiService } from 'src/app/services/api/api.service';
import { AuthService, PERSONAL_DETAILS } from 'src/app/services/auth/auth.service';
import { ReactiveFormService } from 'src/app/services/reactive-form.service';
import { SharedVarService } from 'src/app/services/shared-var.service';

@Component({
  selector: 'app-account-update',
  templateUrl: './account-update.component.html',
  styleUrls: ['./account-update.component.css']
})
export class AccountUpdateComponent implements OnInit {

  public subscriptions: Subscription = new Subscription();
  public updateAccDetailsForm: FormGroup;
  public updateLoginForm: FormGroup;
  public accountModelInput: AccountModel;
  public personalDetailsModelInput: PersonalDetailsModel;

  public accountId: number;
  public responseMsg: string = '';
  public errorMsg: string = '';

  constructor(
    public reactiveFormService: ReactiveFormService,
    public apiService: ApiService,
    public dialog: MatDialog,
    public sharedVar: SharedVarService,
    public authService: AuthService
  ) { }

  ngOnInit(): void {
    this.accountModelInput = this.authService.getRetrievedAccDetails();
    this.personalDetailsModelInput = this.authService.getRetrievedPersonalDetails();

    if (!this.accountModelInput) {
      this.sharedVar.changeException('Account details are null.');
      throw new Error('Account details are null.');
    }

    this.accountId = this.accountModelInput.accId;

    this.updateAccDetailsForm = this.reactiveFormService.initializeUpdateAccDetailsFormControl();
    this.updateLoginForm = this.reactiveFormService.initializeUpdateLoginFormControl();

    this.email.setValue(this.personalDetailsModelInput.email);
    this.contactNo.setValue(this.personalDetailsModelInput.contactNo);
  }

  fieldIsInvalid(field: AbstractControl): boolean {
    return this.reactiveFormService.fieldIsInvalid(field);
  }

  onCancelUpdate(){
    this.email.setValue(null);
    this.contactNo.setValue(null);
    this.oldPassword.setValue(null);
    this.newPassword.setValue(null);
    this.cfmNewPassword.setValue(null);
    this.enableEmailInput();
    this.enableContactNoInput();
  }

  confirmClickedUpdateAccDetails(){
    if(this.updateAccDetailsForm.valid){
      const dialogRef = this.dialog.open(ConfirmDialogComponent, {
        width: '600px',
        data: { type: this.sharedVar.CFM_UPDATE_ACC_DETAILS_DIALOG_TYPE, title: this.sharedVar.CFM_UPDATE_ACC_DETAILS_DIALOG_TITLE }
      });

      dialogRef.afterClosed().subscribe(result => {
        if (result === 'confirm') {
          this.onConfirmUpdateAccDetails();
        }
      });
    } else{
      console.log("update login form failed!");
      this.reactiveFormService.displayValidationErrors(this.updateAccDetailsForm);
    }
  }

  confirmClickedUpdateLogin(){
    if(this.updateLoginForm.valid){
      const dialogRef = this.dialog.open(ConfirmDialogComponent, {
        width: '400px',
        data: { type: this.sharedVar.CFM_UPDATE_PW_DIALOG_TYPE, title: this.sharedVar.CFM_UPDATE_PW_DIALOG_TITLE }
      });

      dialogRef.afterClosed().subscribe(result => {
        if (result === 'confirm') {
          this.onConfirmUpdatePassword();
        }
      });
    } else{
      console.log("update login form failed!");
      this.reactiveFormService.displayValidationErrors(this.updateLoginForm);
    }
  }

  onConfirmUpdateAccDetails() {
    this.errorMsg = "";
    this.responseMsg = "";

    console.log("confirm update account details.");

    const username = this.authService.getAuthenticationUser();

    let accountDetailsModel: AccountDetailsModel = new AccountDetailsModel();
    accountDetailsModel.username = username;
    accountDetailsModel.contactNo = this.contactNo.value;
    accountDetailsModel.email = this.email.value;
    this.sharedVar.updateAccountDetailsModel.accountDetails = accountDetailsModel;

    this.sharedVar.changeSpinner('block');
    this.subscriptions.add(
      this.apiService.updateAccInfo()
      .pipe(finalize(() => this.sharedVar.changeSpinner('none')))
      .subscribe( (resp: any) => {
        if (resp.statusCode != 0) {
          this.errorMsg = resp.resultMessage;
        } else {
          const personalDetails = {
            "email": accountDetailsModel.email,
            "contactNo": accountDetailsModel.contactNo
          };
          localStorage.setItem(PERSONAL_DETAILS, JSON.stringify(personalDetails));
          this.responseMsg = resp.resultMessage;
        }
        this.ngOnInit();
      } , error => {
            console.log(error);
            this.authService.handleError(error);
        }
      )
    );

  }

  onConfirmUpdatePassword() {
    this.errorMsg = "";
    this.responseMsg = "";

    console.log("confirm update password.");

    const username = this.authService.getAuthenticationUser();

    let accountDetailsModel: AccountDetailsModel = new AccountDetailsModel();
    accountDetailsModel.username = username;
    accountDetailsModel.oldPassword = this.oldPassword.value;
    accountDetailsModel.newPassword = this.newPassword.value;
    this.sharedVar.updateAccountDetailsModel.accountDetails = accountDetailsModel;

    this.sharedVar.changeSpinner('block');
    this.subscriptions.add(
      this.apiService.updateAccInfo()
      .pipe(finalize(() => this.sharedVar.changeSpinner('none')))
      .subscribe( (resp: any) => {
        if (resp.statusCode != 0) {
          this.errorMsg = resp.resultMessage;
        } else {
          this.responseMsg = resp.resultMessage;
        }
        this.ngOnInit();
      } , error => {
            console.log(error);
            this.authService.handleError(error);
        }
      )
    );
  }

  enableEmailInput(){
    this.updateAccDetailsForm.controls['email'].enable();
  }

  enableContactNoInput(){
    this.updateAccDetailsForm.controls['contactNo'].enable();
  }

  get email() {
    return this.updateAccDetailsForm.get('email');
  }

  get contactNo() {
    return this.updateAccDetailsForm.get('contactNo');
  }

  get oldPassword() {
    return this.updateLoginForm.get('oldPassword');
  }

  get newPassword() {
    return this.updateLoginForm.get('newPassword');
  }

  get cfmNewPassword() {
    return this.updateLoginForm.get('cfmNewPassword');
  }

}

<div class="alert alert-success" *ngIf="responseMsg"><b>Success: </b> {{responseMsg}}</div>
<div class="alert alert-danger" *ngIf="errorMsg"> <b>Fail: </b> {{errorMsg}}</div>
<div class="card ">
  <div class="text-left">
    <h1 class="card-header">Account Update</h1>
  </div>
  <div class="card-body">
    <hr>
      <mat-tab-group animationDuration="0ms">
        <mat-tab label="Contact Info">
          <br>
          <form [formGroup]="updateAccDetailsForm">
            <div class="form-group row mx-0">
              <label id="ACCOUNT_NO_LABEL" for="account_no_0_Label"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="ACCOUNT_NO">ACCOUNT NO.</span>
              </label>
              <label id="ACCOUNT_NO_INPUT" for="account_no_0_input"
                class="control-label col-sm-4 acc-update-label-text">
                <span id="ACCOUNT_NO"><b>{{accountId}}</b></span>
              </label>
            </div>
            <hr>
            <div class="form-group row mx-0">
              <label id="EMAIL_LABEL" for="email_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="EMAIL">Email:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="text" class="form-control acc-update-section-selection-width no-spinner" formControlName="email"
                    id="email_0" name="email" required>
                  &nbsp;
                  <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" (click)="enableEmailInput()">
                      <i class="fas fa-pencil-alt"></i>
                    </button>
                  </div>
                </div>
                  <label id="email_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(email)}" class="error-text"
                    for="email_0">
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'pattern'">Please enter a valid
                      email address</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(email)) == 'maxlength'">Maximum length is 100
                      characters</span>
                    <span *ngIf="email.hasError('required') && !email.value && !email.pristine">This field is required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="CONTACT_NO_LABEL" for="contact_no_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="CONTACT_NO">Contact No:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="text" class="form-control acc-update-section-selection-width no-spinner" formControlName="contactNo"
                    id="contact_no_0" name="contactNo" required>
                  &nbsp;
                  <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" (click)="enableContactNoInput()">
                      <i class="fas fa-pencil-alt"></i>
                    </button>
                  </div>
                </div>
                  <label id="contact_no_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(contactNo)}" class="error-text"
                    for="contact_no_0">
                    <span *ngIf="contactNo.hasError('required') && !contactNo.value && !contactNo.pristine">This field is
                      required</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'pattern'">Please enter only
                      numeric characters</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(contactNo)) == 'maxlength'">Maximum length is
                      30 characters</span>
                  </label>
              </div>
            </div>
          </form>
          <hr>
          <div mat-dialog-actions align="end">
            <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelUpdate()">
                Cancel
            </button>
            <button class="btn btn-success btn-confirm" type="button" (click)="confirmClickedUpdateAccDetails()">
                Confirm
            </button>
          </div>
          <br>
        </mat-tab>
        <mat-tab label="Login information">
          <br>
          <form [formGroup]="updateLoginForm">
            <div class="form-group row mx-0">
              <label id="OLD_PASSWORD_LABEL" for="old_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(oldPassword)}"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="OLD_PASSWORD">Current Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control acc-update-section-selection-width no-spinner" formControlName="oldPassword"
                    id="old_password_0" name="old_password" required>
                </div>
                  <label id="old_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(oldPassword)}" class="error-text"
                    for="old_password_0">
                    <span *ngIf="oldPassword.hasError('required') && !oldPassword.value && !oldPassword.pristine">This field is
                      required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="NEW_PASSWORD_LABEL" for="new_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(newPassword)}"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="NEW_PASSWORD">New Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control acc-update-section-selection-width no-spinner" formControlName="newPassword"
                    id="new_password_0" name="new_password" required>
                </div>
                  <label id="new_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(newPassword)}" class="error-text"
                    for="new_password_0">
                  <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(newPassword)) == 'maxlength'">Maximum length is
                    20
                    characters</span>
                  <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(newPassword)) == 'minlength'">Minimum length is 5
                    characters</span>
                  <span *ngIf="newPassword.hasError('required') && !newPassword.value && !newPassword.pristine">This field is
                    required</span>
                  </label>
              </div>
            </div>
            <div class="form-group row mx-0">
              <label id="CFM_NEW_PASSWORD_LABEL" for="cfm_new_password_0_Label"
                [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmNewPassword)}"
                class="control-label col-sm-4 acc-update-section-label-width acc-update-label-text">
                <span id="CFM_NEW_PASSWORD">Confirm New Password:</span>
              </label>
              <div class="col-sm-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                  </div>
                  <input type="password" class="form-control acc-update-section-selection-width no-spinner" formControlName="cfmNewPassword"
                      id="cfm_new_password_0" name="cfm_new_password" required>
                </div>
                  <label id="cfm_new_password_error_0" [ngClass]="{'highlightLabel' : fieldIsInvalid(cfmNewPassword)}" class="error-text"
                    for="cfm_new_password_0">
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmNewPassword)) == 'maxlength'">Maximum length
                      is 20
                      characters</span>
                    <span *ngIf="reactiveFormService.fieldErrorPrecedence($any(cfmNewPassword)) == 'minlength'">Minimum length
                      is 5
                      characters</span>
                    <span *ngIf="cfmNewPassword.hasError('required') && !cfmNewPassword.value && !cfmNewPassword.pristine">This
                      field is
                      required</span>
                    <span *ngIf="cfmNewPassword.hasError('passwordMismatch')">Passwords does not match</span>
                  </label>
              </div>
            </div>
          </form>
          <hr>
          <div mat-dialog-actions align="end">
            <button class="btn btn-danger btn-cancel" type="button" (click)="onCancelUpdate()">
                Cancel
            </button>
            <button class="btn btn-success btn-confirm" type="button" (click)="confirmClickedUpdateLogin()">
                Confirm
            </button>
          </div>
          <br>
        </mat-tab>
      </mat-tab-group>
    <br>
  </div>
</div>

// oasisbet-react/src/component/account/AccountUpdate.tsx
import React, { useEffect, useRef, useState } from "react";
import './AccountUpdate.css';
import { Card, Tab, Tabs } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPencil } from "@fortawesome/free-solid-svg-icons";
import { useSessionStorage } from "../util/useSessionStorage.ts";
import SharedVarConstants from "../../constants/SharedVarConstants";
import { validatePassword, validateCfmPassword, validateEmail, validateContactNo, validateRequiredField } from "../util/validation.ts";
import ConfirmDialog from "../common/dialog/ConfirmDialog.tsx";
import { AccountDetailsModel, UpdateAccountDetailsModel } from "../../constants/MockData.js";
import { updateAccInfo } from "../../services/api/ApiService.js";

export default function AccountUpdate(){
    const CONTACT_TAB = 'CONTACT';
    const LOGIN_TAB = 'LOGIN';

    const EMAIL = 'EMAIL';
    const CONTACT_NO = 'CONTACT_NO';

    const CURRENT_PASSWORD = 'CURRENT_PASSWORD';
    const NEW_PASSWORD = 'NEW_PASSWORD';
    const CFM_PASSWORD = 'CFM_PASSWORD';

    const [accountDetails, setAccountDetails] = useSessionStorage(SharedVarConstants.ACCOUNT_DETAILS, {});
    const [personalInfoDetails, setPersonalInfoDetails] = useSessionStorage(SharedVarConstants.PERSONAL_DETAILS, {});
    const [email, setEmail] = useState('');
    const [contactNo, setContactNo] = useState('');

    const [currentPassword, setCurrentPassword] = useState('');
    const [newPassword, setNewPassword] = useState('');
    const [cfmPassword, setCfmPassword] = useState('');

    const [isDialogOpen, setDialogOpen] = useState(false);
    const [dialogData, setDialogData] = useState({ title: '', type: '' });

    const [successMsg, setSuccessMsg] = useState('');
    const [errorMsg, setErrorMsg] = useState('');

    const [accId, setAccId] = useState('');
    const [isEmailDisabled, setIsEmailDisabled] = useState(true);
    const [isContactNoDisabled, setIsContactNoDisabled] = useState(true);
    const [errors, setErrors] = useState({
        currentPassword: '',
        newPassword: '',
        cfmPassword: '',
        email: '',
        contactNo: ''
    });

    const hasEditContact = useRef(false);
    const hasEditPassword = useRef(false);

    useEffect(() => {
        console.log("accountDetails in AccountUpdate: ", accountDetails);
        console.log("personalInfoDetails in AccountUpdate: ", personalInfoDetails);
        const { accId } = accountDetails || {};
        const {email, contactNo} = personalInfoDetails || {};
        console.log("email in AccountUpdate: ", email);
        console.log("contactNo in AccountUpdate: ", contactNo);

        setAccId(accId);
        setEmail(email);
        setContactNo(contactNo);
        setAccountDetails(accountDetails);
        setPersonalInfoDetails(personalInfoDetails);
    }, [accountDetails, setAccountDetails, personalInfoDetails, setPersonalInfoDetails]);

    const onCancel = ((navigateTab) => {
        if(navigateTab === CONTACT_TAB && !isEmailDisabled){
            setEmail('');
        }
        if(navigateTab === CONTACT_TAB && !isContactNoDisabled){
            setContactNo('');
        }
        if(navigateTab === LOGIN_TAB){
            setCurrentPassword('');
            setNewPassword('');
            setCfmPassword('');
        }
    });

    const onSubmit = ((type: string) => {
        console.log("onSubmit Account Update details: ", email, contactNo);
        const validationErrors = {
            currentPassword: '',
            newPassword: '',
            cfmPassword: '',
            email: '',
            contactNo: ''
        };

        if(type === CONTACT_TAB){
            validationErrors.email = validateEmail(email);
            validationErrors.contactNo = validateContactNo(contactNo);
        } else if(type === LOGIN_TAB){
            validationErrors.currentPassword = validateRequiredField(currentPassword);
            validationErrors.newPassword = validatePassword(newPassword);
            validationErrors.cfmPassword = validateCfmPassword(cfmPassword, newPassword);
        }
        setErrors(validationErrors);

        const checkValidation = Object.values(validationErrors).every(error => error === '');
        if (checkValidation) {
            console.log('Account Update Form is valid, submitting form to backend now');
            handleOpenDialog(type);
        } else {
            console.log('Account Update Form is invalid');
        }
    });

    const handleOpenDialog = (type: string) => {
        let dialogTitle = '';
        let dialogType = '';
        dialogTitle = type === CONTACT_TAB ? SharedVarConstants.CFM_UPDATE_ACC_DETAILS_DIALOG_TITLE : SharedVarConstants.CFM_UPDATE_PW_DIALOG_TITLE;
        dialogType = type === CONTACT_TAB ? SharedVarConstants.CFM_UPDATE_ACC_DETAILS_DIALOG_TYPE : SharedVarConstants.CFM_UPDATE_PW_DIALOG_TYPE;
        setDialogData({
            title: dialogTitle,
            type: dialogType,
        });
        setDialogOpen(true);
    };

    const handleCloseDialog = async (result) => {
        setDialogOpen(false);
        if (result === 'confirm') {
          console.log('Confirmed!');
          const request: UpdateAccountDetailsModel = new UpdateAccountDetailsModel();
          const accountDetails: AccountDetailsModel = new AccountDetailsModel();
          
          const username = sessionStorage.getItem(SharedVarConstants.AUTH_USER);
          if(!username){
            console.log("Username is not found in session storage");
            return;
          }  
          accountDetails.username = username
          if(dialogData?.type === SharedVarConstants.CFM_UPDATE_ACC_DETAILS_DIALOG_TYPE){
            accountDetails.contactNo = contactNo;
            accountDetails.email = email;
          } else if(dialogData?.type === SharedVarConstants.CFM_UPDATE_PW_DIALOG_TYPE){
            accountDetails.newPassword = newPassword;
            accountDetails.oldPassword = currentPassword;
          } else {
            console.log("Cannot find dialog type");
            return;
          }

          request['accountDetails'] = accountDetails;
          try {
              const response = await updateAccInfo(request);
              if(response.statusCode !== 0){
                console.log("Error updating account information, response:", response);
                setErrorMsg(response.resultMessage);
              } else {
                //update account information success!
                console.log("Update account information successfully:", response);
                const personalDetails = {
                    "email": email,
                    "contactNo": contactNo
                };
                sessionStorage.setItem(SharedVarConstants.PERSONAL_DETAILS, JSON.stringify(personalDetails));
                setSuccessMsg(response.resultMessage);
                setErrorMsg('');
              }
          } catch (error) {
              //TODO to change this error message to a generic error message shown as red banner
              console.error("Error in handling updating account infomation:", error);
              setErrorMsg("Failed to update account infomation. Please try again.");
          }
        } else {
          console.log('Cancelled!');
        }
    };

    const handlePasswordInputChange = (event, type) => {
        hasEditPassword.current = true;
        if(type === CURRENT_PASSWORD){
            setCurrentPassword(event.target.value);
        } else if(type === NEW_PASSWORD){
            setNewPassword(event.target.value);
        } else if(type === CFM_PASSWORD){
            setCfmPassword(event.target.value);
        }
    };

    const handleContactInputChange = (event, type) => {
        hasEditContact.current = true;
        if(type === EMAIL){
            setEmail(event.target.value);
        } else if(type === CONTACT_NO){
            setContactNo(event.target.value);
        }
    };

    const handleValidation = (inputType) => {
        let validationErrors = {
          currentPassword: '',
          newPassword: '',
          cfmPassword: '',
          email: '',
          contactNo: ''
        };

        if(inputType === CURRENT_PASSWORD){
            validationErrors.currentPassword = validateRequiredField(currentPassword);
        }
        
        if(inputType === NEW_PASSWORD){
          validationErrors.newPassword = validatePassword(newPassword);
        }
        
        if(inputType === CFM_PASSWORD){
          validationErrors.cfmPassword = validateCfmPassword(newPassword, cfmPassword);
        }
    
        if(inputType === EMAIL){
          validationErrors.email = validateEmail(email);
        }
        
        if(inputType === CONTACT_NO){
          validationErrors.contactNo = validateContactNo(contactNo);
        }
    
        setErrors(validationErrors);
    };

    const handleOnBlurInput = (inputType) => (e) => {
        handleValidation(inputType);
    }

    return (
        <div className="container-fluid">
            <br />
            {successMsg && <div className="alert alert-success col-md-6 offset-md-3"><b>Success: </b>{successMsg}</div>}
            {errorMsg && <div className="alert alert-danger col-md-6 offset-md-3"><b>Fail: </b>{errorMsg}</div>}
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Account Update</h2>
                </Card.Header>
                <Card.Body className="card-body">
                <hr />
                <br />
                    <Tabs
                        defaultActiveKey="contact"
                        id="account-update-tab"
                        className="account-update-parent-tab-modal mb-3"
                        >
                        <Tab eventKey="contact" title="Contact Info">
                            <form>
                                <div className="form-group row mx-0">
                                    <label
                                    id="ACCOUNT_NO_LABEL"
                                    htmlFor="account_no_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="ACCOUNT_NO">ACCOUNT NO.</span>
                                    </label>
                                    <label
                                    id="ACCOUNT_NO_INPUT"
                                    htmlFor="account_no_0_input"
                                    className="control-label col-sm-4 acc-update-label-text"
                                    >
                                    <span id="ACCOUNT_NO">{accId}</span>
                                    </label>
                                </div>
                                <hr />
                                <div className="form-group row mx-0">
                                    <label
                                    id="EMAIL_LABEL"
                                    htmlFor="email_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="EMAIL">Email:</span>
                                    </label>
                                    <div className="col-sm-4">
                                        <div className="input-group">
                                            <div className="input-group-prepend"></div>
                                            <input
                                            type="text"
                                            className="form-control acc-update-section-selection-width no-spinner"
                                            id="email_0"
                                            name="email"
                                            value = {email}
                                            onBlur={handleOnBlurInput(EMAIL)}
                                            onChange={(e) => handleContactInputChange(e, EMAIL)}
                                            disabled = {isEmailDisabled}
                                            required
                                            />
                                            &nbsp;
                                            <div className="input-group-append">
                                            <button className="btn btn-outline-secondary btn-pencil" type="button"
                                                onClick={() => setIsEmailDisabled(!isEmailDisabled)}>
                                                <FontAwesomeIcon icon={faPencil} className="pencil-icon"/>
                                            </button>
                                            </div>
                                        </div>
                                        <label id="email_error_0" className={`error-text ${errors.email ? 'highlightLabel' : ''}`} htmlFor="email_0">
                                            {errors.email}
                                        </label>
                                    </div>
                                </div>
                                <div className="form-group row mx-0">
                                    <label
                                    id="CONTACT_NO_LABEL"
                                    htmlFor="contact_no_0_Label"
                                    className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                    >
                                    <span id="CONTACT_NO">Contact No:</span>
                                    </label>
                                    <div className="col-sm-4">
                                        <div className="input-group">
                                            <div className="input-group-prepend"></div>
                                            <input
                                            type="text"
                                            className="form-control acc-update-section-selection-width no-spinner"
                                            id="contact_no_0"
                                            name="contactNo"
                                            value = {contactNo}
                                            onBlur={handleOnBlurInput(CONTACT_NO)}
                                            onChange={(e) => handleContactInputChange(e, CONTACT_NO)}
                                            disabled = {isContactNoDisabled}
                                            required
                                            />
                                            &nbsp;
                                            <div className="input-group-append">
                                            <button className="btn btn-outline-secondary btn-pencil" type="button"
                                                onClick={() => setIsContactNoDisabled(!isContactNoDisabled)}>
                                                <FontAwesomeIcon icon={faPencil}/>
                                            </button>
                                            </div>
                                        </div>
                                        <label id="contact_no_error_0" className={`error-text ${errors.contactNo ? 'highlightLabel' : ''}`} htmlFor="contact_no_0">
                                            {errors.contactNo}
                                        </label>
                                    </div>
                                </div>
                            </form>
                            <hr />
                            <div className="d-flex justify-content-end">
                            <button className="btn btn-danger btn-cancel" type="button"
                                disabled={!hasEditContact.current}
                                onClick={() => onCancel(CONTACT_TAB)}>
                                Cancel
                            </button>
                            <button className="btn btn-success btn-confirm-action" type="button"
                                disabled={!hasEditContact.current}
                                onClick={() => onSubmit(CONTACT_TAB)}>
                                Confirm
                            </button>
                            </div>
                            <br />
                        </Tab>
                        <Tab eventKey="login" title="Login Info">
                        <form>
                            <div className="form-group row mx-0">
                                <label
                                id="OLD_PASSWORD_LABEL"
                                htmlFor="old_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="OLD_PASSWORD">Current Password:</span>
                                </label>
                                <div className="col-sm-4">
                                    <div className="input-group">
                                        <div className="input-group-prepend"></div>
                                        <input
                                        type="password"
                                        className="form-control acc-update-section-selection-width no-spinner"
                                        id="old_password_0"
                                        name="old_password"
                                        onBlur={handleOnBlurInput(CURRENT_PASSWORD)}
                                        onChange={(e) => handlePasswordInputChange(e, CURRENT_PASSWORD)}
                                        value = {currentPassword}
                                        required
                                        />
                                    </div>
                                    <label id="current_password_error_0" className={`error-text ${errors.currentPassword ? 'highlightLabel' : ''}`} htmlFor="current_password_0">
                                        {errors.currentPassword}
                                    </label>
                                </div>
                            </div>
                            <div className="form-group row mx-0">
                                <label
                                id="NEW_PASSWORD_LABEL"
                                htmlFor="new_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="NEW_PASSWORD">New Password:</span>
                                </label>
                                <div className="col-sm-4">
                                    <div className="input-group">
                                        <div className="input-group-prepend"></div>
                                        <input
                                        type="password"
                                        className="form-control acc-update-section-selection-width no-spinner"
                                        id="new_password_0"
                                        name="new_password"
                                        onBlur={handleOnBlurInput(NEW_PASSWORD)}
                                        onChange={(e) => handlePasswordInputChange(e, NEW_PASSWORD)}
                                        value = {newPassword}
                                        required
                                        />
                                    </div>
                                    <label id="newPassword_error_0" className={`error-text ${errors.newPassword ? 'highlightLabel' : ''}`} htmlFor="newPassword_0">
                                        {errors.newPassword}
                                    </label>    
                                </div>
                            </div>
                            <div className="form-group row mx-0">
                                <label
                                id="CFM_NEW_PASSWORD_LABEL"
                                htmlFor="cfm_new_password_0_Label"
                                className="control-label col-sm-4 acc-update-section-label-width acc-update-label-text"
                                >
                                <span id="CFM_NEW_PASSWORD">Confirm New Password:</span>
                                </label>
                                <div className="col-sm-4">
                                    <div className="input-group">
                                        <div className="input-group-prepend"></div>
                                        <input
                                        type="password"
                                        className="form-control acc-update-section-selection-width no-spinner"
                                        id="cfm_new_password_0"
                                        name="cfm_new_password"
                                        onBlur={handleOnBlurInput(CFM_PASSWORD)}
                                        onChange={(e) => handlePasswordInputChange(e, CFM_PASSWORD)}
                                        value = {cfmPassword}
                                        required
                                        />
                                    </div>
                                    <label id="cfmPassword_error_0" className={`error-text ${errors.cfmPassword ? 'highlightLabel' : ''}`} htmlFor="cfmPassword_0">
                                        {errors.cfmPassword}
                                    </label>
                                </div>
                            </div>
                        </form>
                            <hr />
                            <div className="d-flex justify-content-end">
                                <button className="btn btn-danger btn-cancel" type="button"
                                    disabled={!hasEditPassword.current}
                                    onClick={() => onCancel(LOGIN_TAB)}>
                                    Cancel
                                </button>
                                <button className="btn btn-success btn-confirm-action" type="button"
                                    disabled={!hasEditPassword.current}
                                    onClick={() => onSubmit(LOGIN_TAB)}>
                                    Confirm
                                </button>
                            </div>
                            <br />
                        </Tab>
                    </Tabs>
                </Card.Body> 
            </Card>

            <ConfirmDialog
                isOpen={isDialogOpen}
                onClose={handleCloseDialog}
                data={dialogData} />
        </div>
    );
}
