// oasisbet-frontend/src/app/account/account-overview/account-overview.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-account-overview',
  templateUrl: './account-overview.component.html',
  styleUrls: ['./account-overview.component.css']
})
export class AccountOverviewComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card " >
    <div class="text-left">
        <h1 class="card-header">Account Overview</h1>
    </div>
    <div class="card-body">
        <label for="label_balance" class="control-label">Balance</label>
        <div id="label_dashboard_balance_amount" class="dashboard-sidemenu-value">$98.48</div>
        <label for="label_deposit" class="control-label">Deposit</label>
        <div id="label_dashboard_deposit_amount" class="dashboard-sidemenu-value">$50</div>
        <div id="year_to_date" class="text_year_to_date">(Year To Date)</div>
        <label for="label_withdrawal" class="control-label">Withdrawal</label>
        <div id="label_dashboard_withdrawal_amount" class="dashboard-sidemenu-value">$20</div>
        <div id="year_to_date" class="text_year_to_date">(Year To Date)</div>
    </div>
</div>

// oasisbet-react/src/component/account/AccountOverview.tsx
import React from "react";
import './AccountOverview.css';
import { Card } from "react-bootstrap";

export default function AccountOverview(){

    return (
        <div className="container-fluid">
            <Card className="card" style={{tableLayout: 'fixed', width: '100%', marginLeft: '30px' }}>
                <Card.Header className="card-header">
                    <h2>Account Overview</h2>
                </Card.Header>
                <Card.Body className="card-body">
                <label className="control-label">
                    Balance
                </label>
                <div className="dashboard-sidemenu-value">
                    $100.00
                </div>
                <label className="control-label">
                    Deposit
                </label>
                <div className="dashboard-sidemenu-value">
                    $50.00
                </div>
                <div className="text_year_to_date">
                    (Year To Date)
                </div>
                <label className="control-label">
                    Withdrawal
                </label>
                <div className="dashboard-sidemenu-value">
                    $28.00
                </div>
                <div className="text_year_to_date">
                    (Year To Date)
                </div>
                </Card.Body> 
            </Card>
        </div>
    );
}
